### ISSUE TITLE
great idea!

### ISSUE THREAD

**Issue by randomgambit** [ericmjl/pyjanitor#1]
please make sure to make it compatible with Pandas dataframes...
thanks!

**Comment by ericmjl** [comment]
Oh my! I had only just started :smile:.

**Comment by randomgambit** [comment]
its important to go in the right direction from day one :D

**Comment by ericmjl** [comment]
Try it out, @randomgambit! I've pushed up `clean_names()`.

**Comment by randomgambit** [comment]
I am away at the moment but I will try ASAP
I think you should leverage the `.value_counts(sort = TRUE)` method in Pandas, as well as `pd.crosstab()` You could build on them to have a more efficient, and prettier display of tabulations

Thanks!

**Comment by ericmjl** [comment]
As things get ported over, I'll definitely need some help. Would love to see PRs from you, @randomgambit!

**Comment by ericmjl** [comment]
@randomgambit I'm going to close this issue! There's a bunch of new functionality implemented, please check it out!
