### ISSUE TITLE
clean_names breaks for MultiIndex Columns

### ISSUE THREAD

**Issue by JoshuaC3** [ericmjl/pyjanitor#10]
MultiIndex columns returns `expected str not tuple` type error.

If you instead used,
`df.rename(columns=lambda x: x.lower().replace('_', ''))`
this would work for standard and MultiIndex DataFrames.

Can do PR if required.

**Comment by ericmjl** [comment]
@JoshuaC3 definitely would be a welcome addition! Would you be kind enough to put in a PR for this, including an example and test as well?

**Comment by JoshuaC3** [comment]
@ericmjl All done. Added MultiIndex tests and everything passes. Will do PR now.

FYI, I don't have the most experience with writing tests and using GitHub for PRs so please feel free to comment on anything you think I could improve on or should change.

Also, I didn't add any examples as anything using `clean_names` that works for the single Index DataFrame should also work for the MultiIndex.

**Comment by ericmjl** [comment]
Thanks @JoshuaC3! Looking forward to the PR :smile:
