### ISSUE TITLE
Add filter_date function

### ISSUE THREAD

**Issue by szuckerman** [ericmjl/pyjanitor#105]
This issue is to track creating a `filter_date` function, or whatever else you might want to call it.

The main idea is that even though there are already `filter` functions, date filtering is a bit more complex. For example, when filtering strings you can just write a string, but for dates it usually needs to be a `date` or `datetime` object, and not all of them play together nicely.

More important than the above is that when filtering a range, the lines can get really long, like so:

```python
start_date = date(2017, 1, 1)
end_date = date(2018, 1, 1)
df = df[(df.date_column >= start_date) & (df.date_column <= end_date)]
```

I think something like the following is nicer:

```python
df = df.filter_date('date_column', start='2018-01-01', end='2018-01-01')
```
It could also include arguments for `year`, `years`, etc.

**Comment by ericmjl** [comment]
@szuckerman yes, I think this would be a great contribution! Looking forward to seeing it!
