### ISSUE TITLE
Remove Trailing (and Leading) underscores from clean_names

### ISSUE THREAD

**Issue by JoshuaC3** [ericmjl/pyjanitor#12]
Pandas handles this relatively well but would be a good as a kwarg for `jn.clean_names()`.

The default `False` or `None` could leave leading, `True` or `'both'` to remove all and trailing and then pass `'leading'` and `'trailing`' or similar to remove each.

**Comment by ericmjl** [comment]
@JoshuaC3 thanks for raising the issue! So just so I understand correctly, `column_name_` and `_column_name` would become `column_name`, is that right? If so, please send in a PR!

**Comment by JoshuaC3** [comment]
Yes. Exactly. And `_column_name_` would be `column_name`. Will do PR.

Two quick questions on this;

For removing a single underscore would you rather:
1) `'leading'` and `'trailing,
2) `'lead'` and `'trail'`,
3) `'left'` and `'right'`,
4) `'start'` and `'end'`, *
5) other of your choice?

For removing both:
1) `True`, *
2) `'both'` or
3) other of your choice?

* my preferences, but please advise :)

**Comment by ericmjl** [comment]
I'd suggest using a single keyword argument `remove_trailing_underscores`, which accepts either one of: `['start', 'end', 'both']`. By not having mixed `bool` and `str` arguments, it makes for an easier learning pattern for end-users.

Other than that, looking forward to the PR!
