### ISSUE TITLE
"then" function

### ISSUE THREAD

**Issue by szuckerman** [ericmjl/pyjanitor#130]
I had an idea for a function that allows for users to run any arbitrary function in the method chain.

For example, I think it's annoying if someone has their own logic and needs to do this:

```python
def custom_logic(df):
    ...
    return df

df = (df.clean_names()
    .add_column('a_column'))

df = custom_logic(df)
```

Instead, people should be able to do the following:

```python
def custom_logic(df):
    ...
    return df

df = (df.clean_names()
    .then(custom_logic)
    .add_column('a_column')
```

**Comment by ericmjl** [comment]
That's neat, I think I would use it! Being able to use `.then(func)` is more lightweight than adding the pandas-flavor decorator, because I would have one less line of code for the import of pandas-flavor, an X lines less of code for X custom functions!

**Comment by zbarry** [comment]
Can also slap a lambda in there which would be really cool
