### ISSUE TITLE
What's the best name for a "keep null rows" function?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#132]
I have this function implemented in a notebook.

```python
@pf.register_dataframe_method
def keep_null(df, column):
    return df[df[column].isnull() == True]
```

From searching SO and the interwebs, there doesn't seem to be an analogous function like this. Is `keep_null` a good name, or is there a better name for this function?

cc: @szuckerman @zbarry @eli-s-goldberg

**Comment by zbarry** [comment]
Something along the lines of gather_incomplete_rows?

**Comment by ericmjl** [comment]
Do we have a two-word name for it?

**Comment by zbarry** [comment]
`gather_incompleterows` or `gatherincomplete_rows` ? :thinking:

**Comment by szuckerman** [comment]
`gather_recordswithnulls`?

**Comment by zbarry** [comment]
`gather_only_recordswithnullsinthecolumnyouhavespecified`

**Comment by ericmjl** [comment]
You guys... XD

**Comment by ericmjl** [comment]
Maybe there's a better grammar that we can define.

**Comment by zbarry** [comment]
Just a thought... we should be careful to be consistent with making functions that either take one column name or an arbitrary number of column names across relevant functions. I'd lean towards the latter so there isn't as much `.operate_on_column('col1').operate_on_column('col2').operate_on_column('col3').operate_on_column('col4').operate_on_column('col5').operate_on_column('col6').operate_on_column('col7').operate_on_column('col8')...`

**Comment by ericmjl** [comment]
Agreed! I think one example we already have is the `*_column()` paired with `*_columns()` as a companion function. What do you all think about that?

**Comment by zbarry** [comment]
I don't really mind that as long as we consider the energy to maintain both variants of *_ not a problem

**Comment by szuckerman** [comment]
What about dropping the word `column` completely? We could then pass either a `list` or `str` of the columns.

There are many examples of this; one that comes to mind is `groupby` in pandas. You just do `df.groupby(['col1', 'col2'])` or `df.groupby('col1')`. It's a common pattern that I think many people are used to.

This way we don't need to maintain `*_column` and `*_columns` variants.

**Comment by ericmjl** [comment]
On the *_column(s) thing, that sounds like a good idea. Might be a good change for 0.17. (I now realize I bumped minor version too aggressively early on!)

On the keep null rows function name, I just remembered: this is a bit like the opposite of `dropna`, so a helpful name would be `keepna`! What do you all think?

**Comment by szuckerman** [comment]
I think `keepna` is a bit ambiguous since it doesn't imply that the non-na are getting dropped.

I would think `dropnotna` is a bit better for getting the point across that it's the opposite of `dropna`. Also since the `notna` paradigm [already exists in pandas](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.notna.html).
