### ISSUE TITLE
Run notebook example in Binder

### ISSUE THREAD

**Issue by szuckerman** [ericmjl/pyjanitor#149]
There's a new tool, [Binder](https://mybinder.org/), that lets you interactively run a notebook that's hosted in a Github repo in a browser.

Might be a good idea to integrate this with the [notebook example](https://github.com/ericmjl/pyjanitor/blob/dev/examples/pyjanitor_demo.ipynb) and possibly make more intricate examples as well that users can follow interactively.

(See issue #73)

**Comment by ericmjl** [comment]
OOOH!!!!

I love this idea! :smile: I think I will put this up on the Projects board as well.

**Comment by jekwatt** [comment]
I know about the Binder and I can tackle this one if not taken.

Also, I just learned about Google Colab, which seems to be similar to Binder. You may want to check it out.  

https://colab.research.google.com/notebooks/welcome.ipynb
