### ISSUE TITLE
limit column characters

### ISSUE THREAD

**Issue by shantanuo** [ericmjl/pyjanitor#15]
Is there any way to limit the length of column name? for e.g. this_is_very_long_column_needs_truncated should be truncated to left 10 or 20 characters. This may lead to duplicate column names - those should be appended by numbers like this_is_very_long_1 and this_is_very_long_2

**Comment by ericmjl** [comment]
@shantanuo this functionality doesn't exist at the moment. I'm also not fully understanding your use case. Could you help me answer the following questions? Your answers will hopefully guide this discussion.

1. Is truncation desirable?
1. If truncation is desirable, then duplicate column names is a problem. Would suffixing `['_1', '_2', ...]` then be desirable?
1. If truncation is not desirable, then is duplicate column names still a problem?

**Comment by shantanuo** [comment]
I would just incorporate the function "df_column_uniquify" from ...

https://stackoverflow.com/questions/24685012/pandas-dataframe-renaming-multiple-identically-named-columns

Limiting characters in column is important because when I use to_sql method to export pandas data to MySQL, I often get an error if the column names are too long :)

I do always use... 
df.columns = [list of corrected column names]

But your approach of using a class / module for this is much better. Thanks for sharing.

**Comment by ericmjl** [comment]
@shantanuo I'm happy to accept a contribution from you for this functionality. (I'm available to respond to the issue tracker, but in the short term I have deadlines at work, which means I don't have the bandwidth at the moment to implement new features.)

**Comment by shantanuo** [comment]
http://pandas.pydata.org/pandas-docs/version/0.19.2/whatsnew.html#read-csv-has-improved-support-for-duplicate-column-names

Assuming that the duplicate column names problem has been solved, I will suggest to make these changes...
1) Remove special characters like #$%
2) Remove one or more spaces by single dash 
3) Use lowercase
4) Allow max of 35 characters

I use this regular expression:

df.columns=df.columns.str.replace("[^\w\s]+","").str.replace("\s+","_").str.lower().str[:35]

I am not sure how to implement it in this module though :)

**Comment by ericmjl** [comment]
@shantanuo I definitely have to get to writing documentation on how to make a contribution. In the meantime, if you'd like to contribute something, the best thing to do is to contribute a function to the `janitor.functions` module via a Pull Request. 

Most of pyjanitor is just functions to make data cleaning easier by providing single function names that generally do one thing well, and generally return the original DataFrame (unless explicitly returning something else). It comes from the philosophy that data cleaning is part of data modelling, and it generally is a DAG, in which each branch is a linear tape that can be expressed in a method chain.

Let me know if you'd like to discuss more about this.

**Comment by ericmjl** [comment]
@shantanuo thanks to @szuckerman, limit column characters is released in version 0.7.0. Please give it a shot!

**Comment by shantanuo** [comment]
This has addressed the 4th point. The first 3 are still not implemented.

Remove special characters like #$% using str.replace("[^\w\s]+","")
replace one or more spaces by single dash using .str.replace("\s+","_")
lowercase using .str.lower()

We can add more parameters to the function like...
df.limit_column_characters(column_length=7, col_separator='.', case='lower', space='_', special_char=False )

**Comment by shantanuo** [comment]
Thanks to method chaining, I can do this.. 
df.clean_names().limit_column_characters(7)

replace space and lowercase are included in clean_names method. 
There is no way to remove special characters. MySQL does not allow #$% in column names.

**Comment by ericmjl** [comment]
@shantanuo, thanks for the feedback :smile:. 

As usual, I'm always open to pull requests from users of `pyjanitor`. A number of first-timers at open-source contributions have made their first PRs into `pyjanitor`, and I'd be happy to work with you to get your implementations of what is useful into the `pyjanitor` library.
