### ISSUE TITLE
bin_numeric function

### ISSUE THREAD

**Issue by jcvall** [ericmjl/pyjanitor#158]
I cam across this in my data cleaning routine, where I wanted to bin my numeric variables into a categorial column.  Would this be of interest to you to add to pyjanitor?  I don't know if there is already a function for this, I looked but didn't see it.  Let me know if there is something like this already or if you think it is worth adding. Thanks.

![image](https://user-images.githubusercontent.com/20308031/57183915-6b354300-6e81-11e9-9cdd-dd33c41fb402.png)

**Comment by ericmjl** [comment]
@jcvall to the best of my knowledge, this definitely does not exist! I would love to see it in pyjanitor :smile:. Don't forget to pull in the latest changes into your fork of pyjanitor!

**Comment by kurtispinkney** [comment]
@ericmjl If nobody else is currently working on this, I could give it a go.

**Comment by jcvall** [comment]
Sure...no objections. Have at it.

**Comment by ericmjl** [comment]
@jcvall I'd love to invite you to review @kurtispinkney's PR when it comes up! @kurtispinkney, don't forget to reference this issue in your branch name - apparently there's GitHub superpowers associated with putting issue numbers in your branch (i.e. `feature-branch-#291`).

**Comment by szuckerman** [comment]
For inspiration: `R` has a built-in method called `cut` which does this: https://www.dummies.com/programming/r/how-to-create-subgroups-of-data-in-r/

I like that yours has a `labels` arg since that's probably the most important aspect of such a function.
