### ISSUE TITLE
Moving to Azure pipelines

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#160]
Call me a Microsoft fanboy now, but I think Azure pipelines are pretty rad.

The free tier lets us build on all 3 operating systems, with longer timeouts of 6 hours. By contrast, Travis CI only provides Linux testing, and 1 hour before timeouts occur. Being able to test on all 3 operating systems is the biggest draw here.

Moreover, Microsoft devs were on hand here at PyCon to help with the setup and debugging of Azure pipelines. I'm converted. 

I have opened a branch where I am creating a build pipeline for multiple versions of Python and multiple OSes. We will move off Travis CI shortly.

**Comment by zbarry** [comment]
Cool!

**Comment by ericmjl** [comment]
This is addressed by a multitude of issues! #167, #212, #159, #231.
