### ISSUE TITLE
data_dictionary() function

### ISSUE THREAD

**Issue by jcvall** [ericmjl/pyjanitor#162]
I wanted an easy way to create a data dictionary.....I came up with this...

![image](https://user-images.githubusercontent.com/20308031/57188711-757f2d80-6ed1-11e9-94dc-2e3dc93c1340.png)

![image](https://user-images.githubusercontent.com/20308031/57188717-82038600-6ed1-11e9-9a35-8e209a9651da.png)

**Comment by ericmjl** [comment]
I think this could be cool! It wouldn't be a data cleaning function, but could be one of the "utilities". I like where this function is going, and it looks like it could be expandable as well.

**Comment by jcvall** [comment]
If anyone at sprints wants to take this one on, I have no objections!  If they don't
 no worries.  I will put a PR in next week.  I know they will love pyjanitor as much as I do.

**Comment by kurtispinkney** [comment]
Good morning All,
I'm currently at PyCon and am sticking around for a couple of days for the sprints. I've never participated in an open source project before, but when reviewing the different projects available to work on I settled on this one as figured this might be a good issue to work on. If it's cool with all of you I would like to go ahead and attempt to tackle this issue.

**Comment by szuckerman** [comment]
Great idea!

Just some initial thoughts:

1. If you create a new `description` object for each column and you overload `__doc__` within said object, then you can run `help(df.column.description)` to get the column description. I'm not sure exactly how it would be implemented, but that's the general idea. The following works, but seems unstable if you want to use the same `class` over and over again.

```python
class description:
	__doc__ = 'Some description'

column = description()
help(column)
 ```

2. Might be useful to have all this information formatted as some sort of webpage. I.e. `df.data_dictionary()` would open up a browser with all the information outside of `jupyter` or whatever instance the user is running `pyjanitor`.

**Comment by ericmjl** [comment]
@szuckerman this is a super creative idea! I especially like the idea of overwriting the `__doc__` attribute for a new dataframe. 

Perhaps one appropriate way of using this `data_dictionary` function would be instead to load a YAML file that is the data dictionary? Desired API/example below:

```python
# Create dataframe and describe data with a YAML file
df = pd.DataFrame(...).describe_data('data_dictionary.yml')  # with more methods chained afterwards

# Alternatively, create dataframe and describe data with a dictionary.
data_dict = {
    "col1": "description1",
    "col2": "description2",
    ...
}
df = pd.DataFrame(...).describe_data(data_dict)
```

Underneath the hood, what `describe_data` could do is to register a custom accessor, called `data_dictionary`, with methods such as `print()`/`display()` (to send a representation to the screen), `update()` (to update the data dictionary), `validate()` (to report on columns missing a description), and perhaps more. 

Custom accessors might be preferred over overriding `__doc__`, as this is favoured by `pandas`. Functionality to do this is provided in `pandas_flavor` as well: https://github.com/Zsailer/pandas_flavor (scroll to the bottom of the README).

I'm going to tag this one as a good intermediate issue.

**Comment by lphk92** [comment]
I will take a crack at this ticket
