### ISSUE TITLE
Modify our docs build system to showcase notebooks on readthedocs

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#166]
For the project, I would like to build an examples gallery of Jupyter notebooks on a variety of datasets. This would be best showcased by having individual contributors work on cleaning a single dataset in a Jupyter notebook. We would then need a build system to handle the documentation build, such that those notebooks could be featured as part of readthedocs.

This issue would clearly need experience with Jupyter notebooks + Sphinx, and would not be suitable for a beginner to tackle. I would also hold off on tackling this issue until Jupyter notebooks actually live inside the repository.

**Comment by lphk92** [comment]
I'd like to take a crack at this issue!
