### ISSUE TITLE
Case Sensitive True/False kwarg on clean_names

### ISSUE THREAD

**Issue by JoshuaC3** [ericmjl/pyjanitor#17]
Using pyjanitor again today I realised I didn't want to change capitals to lowercase. I think a case sensitive kwarg (default on) would be good.

Happy to do PR for this if you think it is a good idea. One Q on this, what would should the kwarg be called?

Some ideas:
`lower`, `remove_upper`, `drop_case`, `case_sensitive`,...

**Comment by ericmjl** [comment]
Hi @JoshuaC3! Yes, would love a PR on this one. How about `preserve_case` as the kwarg? Would that be a clear enough argument name? 

Don't forget docstrings + tests!

**Comment by JoshuaC3** [comment]
Yes, sounds clearer than my suggestions. I will do `preserve_case=False` as default `True` to preserve.

Will do!
