### ISSUE TITLE
Update contributing docs to explain how to use pyjanitor env in PyCharm

### ISSUE THREAD

**Issue by kurtispinkney** [ericmjl/pyjanitor#170]
When getting ready for the PyCon 2019 sprint I ran into the issue of attempting to setup the conda environment for use within PyCharm. From the Googling I did last night it seems the only way to make use of the provided .yml file is to go through the setup as prescribed in the contributing section and then point the PyCharm interpreter to the environment that gets set up. @kurtispinkney

**Comment by ericmjl** [comment]
@kurtispinkney is working on this one.
