### ISSUE TITLE
Document expected behavior of tests locally

### ISSUE THREAD

**Issue by SorenFrohlich** [ericmjl/pyjanitor#172]
Some of the tests (especially Chemistry test) are expected to fail locally. We should document this, such that new contributors, who runs the test locally, do not worry about failing test that are suppose to fail.

**Comment by ericmjl** [comment]
Thanks for raising the issue, @SorenFrohlich! Please go ahead and tackle it! :smile:

**Comment by jonnybazookatone** [comment]
Maybe as a second step, it might be worth adding logic to skip these tests programmatically in the context you don't expect them to be working.

**Comment by ericmjl** [comment]
Closed by #193.
