### ISSUE TITLE
Propose rearrangement of functions.py

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#175]
`functions.py` is quite long! It could use some refactoring. 

@jk3587 is currently working on a proposed refactoring, and will loop back on this issue.

**Comment by jk3587** [comment]
@ericmjl 
First pass of looking at the various functions, I have organized the functions by functionality:
* **Modify Columns**
  * expand_column
  * concatenate_columns
  * deconcatenate_column
  * remove_columns
  * add_column (perhaps combine the add_columns and add_columns to one function that accepts a list of columns)
  * add_columns
  * transform_column (perhaps combine the transform_column and transform_columns to one function that accepts a list of columns)
  * transform_columns
  * rename_column
  * reorder_columns
  * reset_index_inplace
  * collapse_levels
  * change_type
  * limit_column_characters
  * row_to_names
  * clean_names # cleans column names

* **Modify values**
  * fill_empty
  * convert_excel_date
  * convert_matlab_date
  * convert_unix_date
  * remove_empty
  * coalesce
  * find_replace
  * dropnotnull
  * update_where

* **Preprocessing**
  * min_max_scale
  * impute # could be in modify values
  * label_encode _(imports sklearn for this function but not for min_max_scale)_
  * encode_categorical

* **Select/Filter**
  * filter_string
  * filter_on
  * filter_date
  * filter_column_isin
  * get_dupes
  * get_features_targets
  * select_columns

* **Other/Custom/Utility** _(not sure how to categorize these ones)_
  * then _(this can do any otherfunction that's not built in to pyjanitor)_
  * check _(this may be removed #122 )_
  * round_to_fraction
  * currency_column_to_numeric _(perhaps this can be moved to `pyjanitor.finance`?)_

**Comment by ericmjl** [comment]
Thanks @jk3587! This is a great base on which to do a refactoring of the library. I am going to record my current thoughts here.

Instead of `functions.py`, we should have a few submodules. New structure:

```
- functions/
    - __init__.py  # import from other modules into here.
    - columns.py
    - filter.py
    - values.py  # bad name!!!
    - utils.py
```

**Comment by ericmjl** [comment]
@jk3587, just want to state again that you did a great job with function organization! I'm so glad that you and @ricky-lim could work together to get this onto the docs. I am going to close this issue, as I think it's considered settled! Going forth, we will have to make sure that the docs are kept up-to-date.

**Comment by szuckerman** [comment]
I think that the organization above is great for the functions, but I think that `get_features_targets` should be removed from `functions.py`. It doesn't return the same `DataFrame` and cannot be used as an interim cleaning step.

There are a few other functions I've thought of adding that do something similar (for example, to add  a `to_prophet` method to output the data to [Facebook's Prophet](https://facebook.github.io/prophet/) forecasting module which needs the data in a certain shape) and the main idea is that it completely changes the `DataFrame` and should be used as a "final step" once all other cleaning has been completed.

**Comment by ericmjl** [comment]
> but I think that get_features_targets should be removed from functions.py.

Great that you pointed this out! I am going to raise a separate issue for this one. Perhaps you could raise single issues for a `to_prophet` kind of function as well? I'm not sure what this module would be called... `janitor.ml`? Naming things in programming is hard :).

**Comment by szuckerman** [comment]
Maybe just toss it in the io module? It could be the “o” part.

**Comment by ericmjl** [comment]
Definitely an idea. The "o" part usually refers to on-disk, though, I thought?
