### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by szuckerman** [ericmjl/pyjanitor#176]
@ericmjl @zbarry @jcvall @SorenFrohlich @mdini @kurtispinkney @jekwatt

I want to go through every new issue right now and give a written acknowledgement in addition to a :thumbsup: for each, but there are a lot of them and I don't want to clutter all the issues right now.

Just wanted to give a general "Thanks!" for all the work people are putting in!

**Comment by ericmjl** [comment]
Thanks @szuckerman! Btw, if (and only if) you both have some spare cycles, would you and @zbarry be willing to help me triage issues and tag them with the right labels? Don't worry about getting the labels 100% correct, even I will be making judgment errors in the thick of the sprints.

**Comment by ericmjl** [comment]
@zbarry just trolled us, @szuckerman 😄
