### ISSUE TITLE
Add links to example.rst to readthedocs

### ISSUE THREAD

**Issue by jQwotos** [ericmjl/pyjanitor#177]
- Add hyperlinks to readthedocs documentation on text that recommend using specific methods

_Example_
Change
```
[...] the :py:meth:`clean_names` method. Firstly, we pass [...]
```

to
```
[...] the `:py:meth:clean_names <https://pyjanitor.readthedocs.io/api.html#janitor.functions.clean_names>`_ method. Firstly, we pass [...]
```

**Comment by ericmjl** [comment]
Ok! Thanks for raising this issue, @jQwotos :) I will mark this as taken by you.

**Comment by jQwotos** [comment]
Taking a look more into sphinx and seeing if this can be done in a better way

**Comment by ericmjl** [comment]
@jQwotos just wanted to let you know, a number of RST files have been converted to ipynbs, and now they render on the docs page!

**Comment by jQwotos** [comment]
> @jQwotos just wanted to let you know, a number of RST files have been converted to ipynbs, and now they render on the docs page!

Awesome! Shall I continue to look into this or shall we mark it is closed then

**Comment by ericmjl** [comment]
Let's mark this one as closed. However, because I've seen your effort in making this happen, let's consider your docs contribution done :smile:. Do feel free to tackle a code contribution at this point!
