### ISSUE TITLE
Add tidytuesday example: 2019-04-30

### ISSUE THREAD

**Issue by kimt33** [ericmjl/pyjanitor#178]
Hello! I'm letting you all know that I am working on the dataset from 2019-04-30:
https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-04-30

Related Issue: #165 

It seems that tinytuesday people already use `janitor` to handle data cleanup, so it's not that bad to translate the code from R.

**Comment by ericmjl** [comment]
OK! That's a great contribution, @kimt33 :)

I will mark this as taken by you.
