### ISSUE TITLE
Pandas 23.0.0 Release

### ISSUE THREAD

**Issue by JoshuaC3** [ericmjl/pyjanitor#18]
I noticed the pyjanitor-dev conda environment is running on Pandas 22.X.X. Pandas has just done a [new release](https://pandas.pydata.org/pandas-docs/stable/whatsnew.html) to 23.0.0. I have no idea if this is significant, or if you have plans to keep up to date with the most recent Pandas, but I thought it worth mentioning :)

**Comment by ericmjl** [comment]
Not to worry - I have pyup.io automatically updating pyjanitor every weekend. Thanks for the ping though!
