### ISSUE TITLE
Change janitor.functions.check to a private function

### ISSUE THREAD

**Issue by jk3587** [ericmjl/pyjanitor#182]
`janitor.functions.check` might be an internal function that could be changed to a private function.

**Comment by szuckerman** [comment]
See issue #122. I'm looking at removing `check` altogether 😄.

**Comment by ericmjl** [comment]
Oh, that's right! That point slipped from my mind. Thanks for the reminder, @szuckerman!

**Comment by ericmjl** [comment]
Since @szuckerman is looking at removing `check` altogether, and since we have #122 ongoing, I'm going to close this issue.
