### ISSUE TITLE
The term DAG may be unfamiliar to non programmers. Use more familiar terms

### ISSUE THREAD

**Issue by chrisfs** [ericmjl/pyjanitor#183]
In the beginning of the docs, Data proprocessing is described as " a directed acyclic graph (DAG) of actions taken on data.". I think this term is going to be unfamiliar to people who are not programmers (or not familiar with graph theory). There will be a good deal of confusion since informally graphs are associated with charts . 
Either the term should be removed, or it should be formally defined after a simpler definition of Data Preprocessing. 

Data Preprocessing is a series of actions taken to remove bad data and reformat data so that's it's ready to be used for analysis, Machine learning or visualization.

**Comment by dsouzadaniel** [comment]
Is someone working on this ? Particularly @chrisfs  😄

**Comment by chrisfs** [comment]
I am not working on this right now and was hoping someone more familiar with the term could add a simple definition.

**Comment by dsouzadaniel** [comment]
I've worked a little with Airflow. This doc change is inspired from their docs( which are fantastic! )

I propose changing from
 **this** : 
"Data preprocessing is best expressed as a directed acyclic graph (DAG) of actions taken on data"

**to this** : 
"Data Preprocessing usually consists of a series of steps that involve transforming raw data into an understandable/usable format. These series of steps need to be run in a certain sequence to achieve success. More formally, these steps along with their relationships and dependencies are commonly referred to as a directed acyclic graph (DAG)."

Let me know if this is a useful change @chrisfs @ericmjl & I can start working on it! 🔥

**Comment by chrisfs** [comment]
That seems considerably better. I would add some examples. 
"Data Preprocessing usually consists of a series of steps that involve transforming raw data into an understandable/usable format, such as adding/deleting columns, or dropping null values. "

**Comment by ericmjl** [comment]
@dsouzadaniel, I will assign this one to you! :smile:
