### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#2]
As per title! Having more than one example can be helpful for getting other users to use the package.

**Comment by mamonu** [comment]
will give it a try this weekend :)

**Comment by ericmjl** [comment]
Thank you, @mamonu!

**Comment by szuckerman** [comment]
@ericmjl, based on how the documentation is on readthedocs (specifically the [API section](https://pyjanitor.readthedocs.io/api.html)), it appears that some of the documentation I've been writing would be more suitable there.

Would it make sense to place these in the example input/output in the docstrings so they render in the [API section](https://pyjanitor.readthedocs.io/api.html)?

Seems to make sense to me as the "Examples" on readthedocs are a [bit more freeform](https://pyjanitor.readthedocs.io/example.html#cleaning-column-names).

**Comment by ericmjl** [comment]
@szuckerman yes, that's exactly what I was thinking of when I wrote that option in the PR. Would you be open to kickstarting it? I'd suggest one PR per example, done off a fork off your master branch, so that you master branch mirrors my master branch.

**Comment by ericmjl** [comment]
I am going to add this to the [SciPy sprints projects kanban board](https://github.com/ericmjl/pyjanitor/projects/2?fullscreen=true).

I am also considering making this a pre-requisite before new functions can be added, i.e. improve the documentation behind one of the functions, before being allowed to contribute a new one. An evil plan to get others involved in the project.

**Comment by ericmjl** [comment]
Closing this issue, as I think we have a suite of starter examples inside the docs page!
