### ISSUE TITLE
[ENH] clean_names() in functions is too verbose

### ISSUE THREAD

**Issue by jekwatt** [ericmjl/pyjanitor#203]
* Improvement can be made by using re
* remove `_`if column_name begins with `_`
* change`%`to `_pct_` or other suggested value

**Comment by jekwatt** [comment]
non-alphanumeric characters includes punctuations and symbols

punctuations includes : ! @ # & ( ) – [ { } ] : ; ', ? / *

symbols includes: ` ~ $ ^ + = < > “

By using re, non-alphanumeric characters `\W` can be easily replaced to `_`.

**Comment by ericmjl** [comment]
@jekwatt I would like to assign you to this PR please!

**Comment by jekwatt** [comment]
I've created a branch `issue-203` and set upstream of this (I don't see it now and I may have to do it again).  When ready to open a PR, I will reference this issue.
