### ISSUE TITLE
GroupBy, aggregate, but keep within the original DataFrame

### ISSUE THREAD

**Issue by jonnybazookatone** [ericmjl/pyjanitor#204]
I often want aggregates over different values in a dataframe, but still want to see those values alongside non-aggregate values, which can require multiple non-chainable steps of code.

Wonder if anyone has an example of this, or has an opinion?

**Comment by szuckerman** [comment]
Looks good! This is a common practice in SQL using [window functions](https://docs.aws.amazon.com/redshift/latest/dg/r_Examples_of_sum_WF.html). 

I think what you've done in the PR mimics most of the functionality, but if you're looking for inspiration, there's [a ton of documentation](https://docs.aws.amazon.com/redshift/latest/dg/c_Window_functions.html) to give you more ideas.

**Comment by jonnybazookatone** [comment]
Yes, equally as hairy in SQL...
