### ISSUE TITLE
[INF] Need infrastructure to auto-build changelog.

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#225]
This would require us to squash commits upon merge, changing the way that merges are currently done.

The advantage here would be an auto-tracking of changelog! Much better than what we currently have, which is no changelog at all :smile:.

**Comment by hectormz** [comment]
@ericmjl looks like this was created when there was no changelog. Is this issue still present? Or instead of each PR coming with a line added to the changelog, do you want to add several lines whenever a version is bumped/release made?

**Comment by ericmjl** [comment]
@hectormz been thinking about this on-and-off over the past year now (!!!). I think the current system we have, where we have contributors add changelog lines is a "mama bear goldilocks good enough" way of working. I'm going to go ahead and close this - the ultimate for me would be auto-release on every PR merge, but that's very complicated :).

**Comment by hectormz** [comment]
I think adding per PR may be difficult, but there may be some existing Github Action out there that could be used or modified.

Here are some I've found that might have hints for what we'd want to do:

- [generate-changelog-action](https://github.com/marketplace/actions/generate-changelog-action)
- [auto-changelog-action](https://github.com/CharMixer/auto-changelog-action)
- [release-notes-generator-action](https://github.com/marketplace/actions/release-notes-generator-action)

And napari has a [script/template to generate release notes](https://github.com/napari/napari/blob/master/docs/release/generate_release_notes.py) with an [update on the way ](https://github.com/napari/napari/pull/1043)


Maybe something to think about again in the future
