### ISSUE TITLE
Install fails with Python 3.7

### ISSUE THREAD

**Issue by mattharrison** [ericmjl/pyjanitor#24]
Due to pinning of sklearn version, it fails on 3.7. Need to change the dep for sklearn from ``==`` in ``requirements.txt`` to ``=>``

**Comment by ericmjl** [comment]
@mattharrison got it!

**Comment by ericmjl** [comment]
I've just pushed a new release; I hope this is working!

**Comment by mattharrison** [comment]
Successfully installed pyjanitor-0.3.2
