### ISSUE TITLE
[DOC] clarify docstring for encode_categorical

### ISSUE THREAD

**Issue by catherinedevlin** [ericmjl/pyjanitor#254]
For those not familiar with Pandas' `category` dtype, the docstring for `encode_categorical` isn't very clear as it stands.

**Comment by ericmjl** [comment]
Yes, thank you for the catch, @catherinedevlin! 

Would you be kind enough to elaborate on where the lack of clarity currently is? In particular, what might a newcomer expect that is different from the behaviour of `encode_categorical`?

**Comment by catherinedevlin** [comment]
The old docstring doesn't make clear that it's talking specifically about a Pandas `category` dtype, which many users may not know about.  Without knowing better, I expected `encode_categorical` to do something visible to the data, not just change its dtype - maybe replace the string values with an integer, as if for a foreign key.

**Comment by catherinedevlin** [comment]
Closed by https://github.com/ericmjl/pyjanitor/pull/266
