### ISSUE TITLE
[ENH] find_replace on multiple columns 

### ISSUE THREAD

**Issue by mdini** [ericmjl/pyjanitor#255]
modify find_replace to be applicable to a list of columns

**Comment by NapsterInBlue** [comment]
I don't know a lot about decorators, but it seems like we've got a similar pattern at multiple points in the codebase:

- [1](https://github.com/ericmjl/pyjanitor/blob/ceca343d4dad07aa7602ff7f6742af96c560e872/janitor/functions.py#L249)
- [2](https://github.com/ericmjl/pyjanitor/blob/ceca343d4dad07aa7602ff7f6742af96c560e872/janitor/functions.py#L302)
- [3](https://github.com/ericmjl/pyjanitor/blob/ceca343d4dad07aa7602ff7f6742af96c560e872/janitor/functions.py#L361)
- etc

Is this an appropriate use for them?

**Comment by ericmjl** [comment]
Perhaps so! I have always been a bit lazy and just provided `X_column(s)` as corresponding pairs as the need arose. I'd like to see a bit more standardization of my laziness into something more formal here. @NapsterInBlue, do you have any ideas to propose? If you do, please post them here, so we can flesh out the implementation in the open first.

**Comment by zbarry** [comment]
Could this also support destination column(s) so as to not replace the values in the original column(s)? Also, some sort of `check_exists` (default could be `False`) mode or whatever which ensures that the keys in your dict are present could be handy when people want such a sanity check.

**Comment by ericmjl** [comment]
> Could this also support destination column(s) so as to not replace the values in the original column(s)? 

`find_replace`, semantically, I think means replacing the existing values. We can debate this though.

In terms of creating a new column, I think `join_apply` would be the right way to do this.

**Comment by zbarry** [comment]
`transform_column` would then follow the same logic, no?

**Comment by ericmjl** [comment]
That's true too. We need a vote.

**Comment by zbarry** [comment]
The way to then do this would then be:

`df.join_apply(lambda df: df.copy().[function]('column_name', ...)['column_name'], 'new_column_name')`

where `[function]` is a function that operates in place on a column, right? (or something like that). In place functions also conflict with the mission to make pyjanitor functions not modify the original dataframe, as well, as far as I can see.

**Comment by ericmjl** [comment]
Cognitive load wins the argument for me. I'm out right now, do you have time to do the PR?

**Comment by zbarry** [comment]
Not at the moment; I'm on a deadline to get some data to a collaborator

**Comment by ericmjl** [comment]
Btw:

> In place functions also conflict with the mission to make pyjanitor functions not modify the original dataframe, as well, as far as I can see.

There's a difference between in-place in memory and in-place assigned to the original. IIRC, `find_replace` should be the latter, i.e. the original dataframe is copied (I think).

**Comment by zbarry** [comment]
~~hence the strikethrough :thinking:~~

**Comment by nickdelgrosso** [comment]
I would like to propose adding both multi-column, single-mapping support and multi-column, multi-mapping support to the existing find_replace() functionality.  To support both cases, I propose splitting find_replace() into an additional function, find_replace_all():

# Example API
```python
def find_replace_all(mapping: Dict, column_names: Union[List, str]): pass
def find_replace(**mappings: Dict[str, Dict]): pass
```

## Example Usages:

```python
df.find_replace_all({-9999: np.nan}, column_names=['column1', 'column2'])
```
```python
df.find_replace(column1={-9999: np.nan}, column2={'none', np.nan})
```
An interesting benefit is that find_replace() can also handle multi-column, single-mapping if pre-assignment or the new walrus is used:

```python
m = {-9999: np.nan}
df.find_replace(column1=m, column2=m)
```

```python
df.find_replace(column1=m:={-9999: np.nan}, column2=m)
```

**Comment by zbarry** [comment]
@ericmjl

**Comment by ericmjl** [comment]
I’m in favour of the propose API, @nickdelgrosso!

**Comment by ericmjl** [comment]
5 months later (with many apologies to all who have been watching this issue), I think @nickdelgrosso's proposed API is better than the current API. Reasons are mainly for readability: "`find` and `replace` in `columnA` this `mapping`, in `columnB` this `other_mapping`, etc."
