### ISSUE TITLE
[INF] requirements-dev.txt needed

### ISSUE THREAD

**Issue by catherinedevlin** [ericmjl/pyjanitor#257]
`make check` requires `black` and `isort`, which aren't included in requirements.txt.  We should make a requirements-dev.txt containing them.

Should the requirements for building docs go in there, too?  Otherwise people installing pyjanitor will get Sphinx, etc. whether they ever want to build the documentation or not.

**Comment by Juanlu001** [comment]
`requirements.txt` are [for applications](https://caremad.io/posts/2013/07/setup-vs-requirement/), what about using `extras_require` in `setup.py`, or even [`setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)?

**Comment by NapsterInBlue** [comment]
Great idea. In turn, we should be sure to update the "Contributing" part of the docs!

**Comment by ericmjl** [comment]
Thanks @catherinedevlin, @Juanlu001 and @NapsterInBlue! Let me finalize the checklist here:

- [ ] Create a `requirements-dev.txt` with `black`, `isort`, `sphinx`, `nbsphinx`, and others.
- [ ] Update the `CONTRIBUTING.rst` file.
- [ ] (optional) Update Azure pipelines with a venv-based setup on macOS, Linux and Windows.

**Comment by catherinedevlin** [comment]
OK, I'll work this one myself if that's good with everybody!
