### ISSUE TITLE
[ENH] regex_edit() function

### ISSUE THREAD

**Issue by jcvall** [ericmjl/pyjanitor#273]
This is something I do often to clean up some data.  I use the replace function inside of the pyjanitor transform_column or transform_columns function.  I wonder if it would be better to create a single function called regex_edit() or to leave it like how I do it and document it for others. Thoughts?

![image](https://user-images.githubusercontent.com/20308031/57317087-4af5c600-70c5-11e9-89ee-fc3c775a43bb.png)

**Comment by jk3587** [comment]
While typing up an example usage notebook, I also ran into this convenience issue. I used an implementation of the other example notebooks that did something like this:

```python
@pf.register_dataframe_method
def str_replace(df, column_name: str, pat: str, repl: str, *args, **kwargs):
    """Wrapper around df.str.replace"""

    df[column_name] = df[column_name].str.replace(pat, repl, *args, **kwargs)
    return df
```

Wondering if all the pandas string methods can be turned into pyjanitor functions?

**Comment by samukweku** [comment]
#360 covers this; I suggest closing it?

**Comment by ericmjl** [comment]
Do the honors, @samukweku :smile:

**Comment by samukweku** [comment]
Haha! honored!
