### ISSUE TITLE
[ENH] Remove uses of `.apply()` in favor of pandas functions

### ISSUE THREAD

**Issue by lphk92** [ericmjl/pyjanitor#274]
There are several places in the code where `.apply()` is being used, but there are pandas optimized functions that could be used instead for better performance.

It would be good to go through all of the uses of `apply()` in the code to see what can be replaced with more performant functions.

**Comment by ericmjl** [comment]
Indeed! I have labelled this one as a "good intermediate issue". 

The workflow probably would look like this:

- comb through the codebase and find the ones where `.apply()` is used
- identify whether an analogous pandas-optimized function exists
- replace the function and test

@lphk92, do you happen to have an example function that you could document here? That can be taken up by another newcomer.

**Comment by hectormz** [comment]
I'll take this. I started to replace some. I've found at least one where there doesn't seem to be a non-apply pandas method. I'll report what I can't replace and see if anyone has a suggestion

**Comment by hectormz** [comment]
At this point I have converted most `apply()`s I've found. One thorn has been `cleaning_style='accounting'` in `currency_column_to_numeric()` I've tried a couple methods that remove the use of `apply()`, which are either slower entirely, or not  consistently faster.

This is essentially what exists now:

```python
def _clean_accounting_column(x: str) -> float:
    y = x.strip()
    y = y.replace(",", "")
    y = y.replace(")", "")
    y = y.replace("(", "-")
    if y == "-":
        return 0.00
    return float(y)

df[column_name].apply(_clean_accounting_column)
```

The best solution I've come up with is:

```python
# strip white space
df.loc[:, column_name] = df[column_name].str.strip()

replace_dict = {
	",": "", 
	")": "", 
	"(": "-"
	}
# Replace substrings according to dictionary
df[column_name] = df[column_name].str.translate(str.maketrans(replace_dict))

# Replace `-` with 0
df[column_name].replace({'-':0}, inplace=True)

# Convert column to floats
df.loc[:, column_name] = df[column_name].astype(float)
```

I compared these two approaches with a range of dataframe sizes, running the methods on the same dataframe 100 times each, and calculating mean, std.

![process_time](https://user-images.githubusercontent.com/23343812/66706377-89cc1f80-ece6-11e9-8bbc-b5d72fd2b649.png)

I'm open to any other ideas people may have.  Any thoughts @ericmjl @zbarry @szuckerman and others? Or this might just be a place to leave `apply()` in

**Comment by hectormz** [comment]
Here are the worse methods I've tried:

```python
# Method C
df.loc[:, column_name] = df[column_name].str.strip()

df.loc[:, column_name] = df[column_name].str.replace(",", "")
df.loc[:, column_name] = df[column_name].str.replace(")", "")
df.loc[:, column_name] = df[column_name].str.replace("(", "-")

df.loc[df[column_name] == "-", column_name] = 0.0
df.loc[:, column_name] = df[column_name].astype(float)

# Method D
df.loc[:, column_name] = df[column_name].str.strip()

replace_dict = {",": "", ")": "", "(": "-"}

df[column_name] = df[column_name].str.translate(str.maketrans(replace_dict))


df.loc[df[column_name] == "-", column_name] = 0.0
df.loc[:, column_name] = df[column_name].astype(float)

# Method E
df.loc[:, column_name] = df[column_name].str.strip()

replace_dict = {",": "", ")": "", "(": "-"}

df[column_name] = df[column_name].str.replace('(','-').str.translate(str.maketrans('','',"),"))


df.loc[df[column_name] == "-", column_name] = 0.0
df.loc[:, column_name] = df[column_name].astype(float)
```

**Comment by ericmjl** [comment]
Oh my, I definitely left this one hanging! @hectormz really sorry about this, I was only _just_ reviewing old issues and PRs before I _really_ go on vacation.

I’d be inclined to go with the method that gives best speed performance first, memory performance next. It looks like, according to your measurement, leaving `apply` alone in this case is the best design choice available to us for now, short of importing the big gun `numba` (haha, please, don’t :smile:).

Is there anything else left on this issue?

**Comment by hectormz** [comment]
@ericmjl no worries! I'll see if any new `apply` instances have been added in the meantime. Otherwise I'll make a PR with what I have
