### ISSUE TITLE
[DOC] General Functions page should allow for clicking to access the actual function docstring

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#304]
Right now, it's just a table. However, we need to be able to link each function to their actual docstring, so that one can figure out how to use the function.

**Comment by zbarry** [comment]
Hmm, this seems to be somewhat high priority, because people can no longer read the API docs to figure out how to use most pyjanitor functions...

**Comment by zbarry** [comment]
Did you change anything? Turns out they are links:

https://pyjanitor.readthedocs.io/reference/general_functions.html

**Comment by ericmjl** [comment]
Yes, I think fixed this in one of those mega-PRs - #331 was the one.
