### ISSUE TITLE
[DOC] Feedback on the PyCon 2019 pyjanitor sprint

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#307]
cc: @jekwatt @kurtispinkney @lphk92 @jonnybazookatone @SorenFrohlich @dave-frazzetto @dsouzadaniel @Eidhagen @mdini @kimt33 @jack-kessler-88 @NapsterInBlue @jk3587 @ricky-lim @catherinedevlin @StephenSchroed

Thank you all for coming to the pyjanitor sprints! I had a ton of fun sprinting with you all, and I am so humbled that you all came on board and quickly made so many improvements to the code, documentation, infrastructure, tests, and more!

I'd like to know how the sprints could have gone better. If you would be kind enough to do so, could you please provide some feedback [here](https://ericma1.typeform.com/to/L1Y14n)?

I have asked for your Twitter handles; I wrote a sprint post-mortem for myself to reflect on it, and will be tweeting you all shortly too.

**Comment by ricky-lim** [comment]
Hi Eric,

A subgroup of sprinters, at least 4 people (@dsouzadaniel, @NapsterInBlue, @jk3587 + me) , analyzed with [azure](https://azure.microsoft.com/en-us/try/cognitive-services/my-apis/?apiSlug=face-api), seem to be happy and one (the lady in between) is being missed annotated (perhaps someone should do PR on this)

![pyjanitor_annotated](https://user-images.githubusercontent.com/10878392/57596257-039a8a00-754a-11e9-91fb-8ce2d56c9dca.png)

**Comment by ericmjl** [comment]
Awww, you all were so fun to sprint with!!
