### ISSUE TITLE
[ENH] get_features_targets should be moved out of functions.py

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#318]
# Brief Description of Fix

Currently, the docs show that `get_features_targets` is in `functions.py`. @szuckerman suggests that it should be moved out of `functions.py`, because it doesn't return the same DataFrame and cannot be used as an interim cleaning step.

I would like to propose a change, such that we create a new submodule called `ml.py`. There, we can house the functions that return an ML-compatible dataframe, rather than a modified/cleaned version of the same one (subtle differences, yes), with `get_features_targets` being one of the relevant functions.

**Comment by hectormz** [comment]
@ericmjl Are there other potential functions in `functions.py` that would also be good candidate for `ml.py`, or should we just start with `get_features_targets` ?

**Comment by ericmjl** [comment]
@hectormz thanks for keeping this one alive! 

From memory, I think only `get_features_targets` is relevant to an `ml.py` submodule, though there might be a case for `min_max_scale` and `label_encode`, as those replicate sklearn-like functionality. 

What are your thoughts here?

**Comment by hectormz** [comment]
I like the idea about targeting functions that don't:

> return the same DataFrame and cannot be used as an interim cleaning step.

I think that there are likely functions (as you mentioned) that have some ML functionality, but they still make sense to me in the normal `pyjanitor` workflow. So I would focus on functions that are **exclusively** ML functions.

I'm looking through the functions (main functions only, not the existing modules), but it may be only `get_features_targets` for now.
