### ISSUE TITLE
[DOC] Sphinx code block width needs to be wider

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#325]
Firefox & Chrome on macOS

<img width="705" alt="image" src="https://user-images.githubusercontent.com/4762711/57571327-91effe00-73da-11e9-8b42-034ac4770008.png">

**Comment by ericmjl** [comment]
Is it scrollable, @zbarry?

**Comment by zbarry** [comment]
Mhm

**Comment by zbarry** [comment]
@ericmjl - you can see throughout the inline docs notebooks (really cool, by the way) that stuff gets cut off. I think we can afford to increase that column's width a little bit... right now, it's pretty skinny.

**Comment by ericmjl** [comment]
:thumbsup:

Let me rename this issue.

**Comment by NapsterInBlue** [comment]
The code itself has been cleaned up since this issue was opened. Windows Chrome screenshot:

![image](https://user-images.githubusercontent.com/3505365/61995620-c5950880-b058-11e9-820e-958136a47f94.png)

Do we still wanna tinker w/ the CSS? Or are we good to close the issue?

**Comment by ericmjl** [comment]
I think let's close the issue! Thanks for resurfacing, I haven't had the chance to look through the issues for a while.

**Comment by NapsterInBlue** [comment]
Sounds good!

Was inspired by the "contribute to stuff" keynote at PyOhio and wanted to troll through my favorite open source pandas extention for open commits.

Hope things are great!
