### ISSUE TITLE
[DOC] Remove reference to `reset_index_inplace` in example notebook

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#326]
#262 

https://github.com/ericmjl/pyjanitor/blob/dev/examples/notebooks/pyjanitor_intro.ipynb

> .reset_index_inplace() is a pyjanitor stand-in for df.reset_index(inplace=True), because the latter does not return the DataFrame when the in place mode is used and is therefore not chainable.

**Comment by qtson** [comment]
I would like to work on this issue
