### ISSUE TITLE
[DOC] TidyTuesday examples need to be cleaned up

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#327]
https://pyjanitor.readthedocs.io/notebooks/tidytuesday_20190423.html

* Title should be changed
* Needs a pyjanitor intro rather than someone else's text copy-pasted (though maybe this could be included as a quote block to make it explicit that this is not janitor content)
* Python warnings in output blocks need to be removed
* Resulting dataframes from each step should be previewed in cell output

https://pyjanitor.readthedocs.io/notebooks/tidytuesday_20190430.html

* Show original dataframe previews in cell output
* Show resulting dataframe previews in cell output

**Comment by ericmjl** [comment]
Great catches, @zbarry! Thanks for doing these checks :smile: :tada:

**Comment by jk3587** [comment]
@zbarry I'll fix up https://pyjanitor.readthedocs.io/notebooks/tidytuesday_20190423.html

**Comment by zbarry** [comment]
Think this only resolves for one of the notebooks.
