### ISSUE TITLE
[BUG] filter_date unnecessarily enforces column name to be a string

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#339]
@ericmjl if you could confirm this is truly not necessary, I'll remove the `check` line in my typing/code refactoring PR I'm working on

**Comment by ericmjl** [comment]
It could be unnecessary, for sure. 

Canonically, we usually use a string column name, but I guess that doesn't _exactly_ have to be necessary.

**Comment by zbarry** [comment]
Yeah, my thought on it is that 99% of the time, it's going to be a string, but if there's no obvious benefit from restricting users from doing something (like passing something that's not a string), we might want to lean towards the side of giving them as much freedom we can to use the package how they want.

**Comment by ericmjl** [comment]
Agreed here.

Beyond this, I wonder where having opinionated choices (i.e. the way `black` does it) might be a good idea in `pyjanitor`?

**Comment by szuckerman** [comment]
I see this is closed, but what's the rationale for having the column name not necessarily be a string?

What else is someone going to put in there? The only thing I could think of would be a `list` (if they want to filter multiple columns at once, but would make more sense to chain multiple `filter_date`s together) or an integer for a column index. And it's bad practice to use numerical indices unless you absolutely have to.

**Comment by ericmjl** [comment]
Yeah, it got closed as part of the PR.

> What else is someone going to put in there? The only thing I could think of would be a list (if they want to filter multiple columns at once, but would make more sense to chain multiple filter_dates together) or an integer for a column index. And it's bad practice to use numerical indices unless you absolutely have to.

@szuckerman great point, your thought is related to what I was thinking about when I raised the question above re: having opinionated choices. Perhaps we should be opinionated here, and guide users to best practices?
