### ISSUE TITLE
[DOC] Update Azure build status

### ISSUE THREAD

**Issue by HectorM14** [ericmjl/pyjanitor#346]
# Brief Description of Fix

I noticed we still have the Travis CI build status badge, which is failed because we switched to Azure Pipelines. I collected the links that we would apparently use:

```
.. image:: https://dev.azure.com/ericmjl/Open%20Source%20Packages/_apis/build/status/ericmjl.pyjanitor?branchName=dev
    :target: https://dev.azure.com/ericmjl/Open%20Source%20Packages/_build/latest?definitionId=2&branchName=dev
```

These links can be generated from a menu on the build's page. However, these are for the `dev` branch, and I'm not sure if it should be for `dev` or `master` moving forward.

# Relevant Context

- [Get Build Badge Data](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/badge/get%20build%20badge%20data?view=azure-devops-rest-5.0)
- [README.rst](https://github.com/ericmjl/pyjanitor/README.rst)

**Comment by ericmjl** [comment]
@HectorM14 please feel free to PR in! Everything goes onto the `dev` branch. Once we have one or two more PRs in, I will cut a 0.17 release.

**Comment by HectorM14** [comment]
Done! Exciting!
