### ISSUE TITLE
[ENH/BUG] Assertions used in place of raising errors in various functions

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#354]
* `concatenate_columns`
* `deconcatenate_column`
* `DataDescription`
* `clean_names`
* `encode_categorical`
* `label_encode`
* `fill_empty`

**Comment by hectormz** [comment]
@zbarry Should **all** assertions raise `JanitorError` instead?

**Comment by ericmjl** [comment]
So far, `JanitorError` has been used as a catch-all. We can definitely start there, but maybe some judicious use of `ValueError` could be helpful.

**Comment by hectormz** [comment]
@ericmjl sure. So should all assert statements in the codebase raise exceptions instead? Or are there only certain asserts that should raise?

Makes sense to use `ValueError` at times. `JanitorError` makes it abundantly clear where the error is originating, but `ValueError` is more helpful.

**Comment by ericmjl** [comment]
Yes, I think the assertions should be changed to errors being raised.

**Comment by hectormz** [comment]
Got it, I can take this issue on! I'll report back if I find some pattern of use that might warrant specific exceptions etc

**Comment by ericmjl** [comment]
Alrighty! Thanks @hectormz! :smile:

**Comment by zbarry** [comment]
@hectormz - I’ve been replacing assertions with standard Python errors, yeah. I haven’t used JanitorError myself afaikr
