### ISSUE TITLE
[ENH] Wrap pandas string methods

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#360]
# Brief Description

One thing that might be nice is to wrap all of the string methods such that they are now method-chainable.

If this could be done programmatically, that would be awesome. Otherwise, manually wrapping ones of interest, and building up a submodule of string method operations, would be a superb alternative.

# Example API

The example API can be found in [this notebook](https://github.com/ericmjl/pyjanitor/blob/dev/examples/notebooks/tidytuesday_20190423.ipynb).

**Comment by szuckerman** [comment]
What about this?

Instead of:

```python
@pf.register_dataframe_method
def str_join(df, column_name: str, sep: str, *args, **kwargs):
    """
    Wrapper around `df.str.join`
    Joins items in a list.    
    """

    df[column_name] = df[column_name].str.join(sep)
    return df
```

Make the function generic:

```python
@pf.register_dataframe_method
def str(df, method_type, column, *arg, **kwargs):
    df[column_name] = getattr(df[column_name].str, method_type)(sep)
    return df

df.str('join', 'column_name', sep=',')
```

I've been looking for a way to make the function name generic, too, (i.e. so we could use `df.str_join`
and in pyjanitor the function name would be something like `df.str_` + `method_name`) but that looks like you have to use `setattr` within a `class` and might not work with `@pf.register_dataframe_method`.

**Comment by eyaltrabelsi** [comment]
@szuckerman @ericmjl I would like o work on this.

**Comment by samukweku** [comment]
@ericmjl ,  Kindly assign to me if this is still available. @eyaltrabelsi asked first though, so please let’s check that he/she is still interested in it. Thanks

**Comment by ericmjl** [comment]
Oh my, it looks like I totally let this one drop. @eyaltrabelsi, I'm so sorry. 

@samukweku, given the time interval, I think you can go ahead without any issues. Please do so :smile:.

**Comment by ericmjl** [comment]
:tada:
