### ISSUE TITLE
[INF] Moving to an automatic release per PR?

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#361]
@zbarry and @szuckerman I'm super tempted to move pyjanitor to continuous releases. What do you all say? @HectorM14 I'd also appreciate your input on this, given your numerous doc and code contributions thus far.

This is inspired by Hypothesis. Every PR that gets merged has to indicate whether this is one of a major, minor or patch release. (The wave of doc PRs we've got would constitute patch releases each.)

I'm also seeing how automatic infrastructure to build a changelog can help with recording contributions better. 

Finally, automatic releases means I don't have to worry about cutting a release locally.

We already have conda-forge-based automation that gives us automatic conda-forge builds upon new PyPI releases (it's thanks to the conda-forge team that all PyPI-released packages get updated on conda-forge's CI system). 

What do you all think?

**Comment by HectorM14** [comment]
Interesting proposal @ericmjl. I think the Testing/CI is sufficiently robust at the moment. 

How do you envision the future of `pyjanitor` development? I suppose that a lot of the obvious functions have been implemented, and there will be various bug fixes/improvements/new functions in the future (especially the field-specific ones). But there will always be a list of user and contributor documentation improvements and examples to be made. New functions are nice, but better documentation for usage is probably even more high yield, and should get out to the users quickly. 

Would the intensity of PR review change, or would we just indicate what type of release it would be?

Could patch releases accumulate and release at most every `n` days in the event of a flurry of PRs?

I'm curious to see what everyone else has to say, but I'm not opposed to the idea.

**Comment by szuckerman** [comment]
My initial reaction is to say "go for it!", but I think that @HectorM14 has a good point regarding documentation and figuring out the overall future impact as well.

However, I think the points you make with the changelog and release types might be good to start sooner rather than later. And that doesn't mean we can't update documentation in the meantime :smile:.

**Comment by HectorM14** [comment]
Glad to see the new release and that it is being implemented. Are there closed PRs that show this in action yet?

**Comment by ericmjl** [comment]
No, none yet, but I'm working on the tooling steps. I'm still a bit confused as to how things have to happen though. Hypothesis' style is intricate! Maybe if we went to calendar-versioning, things would be easier haha...

**Comment by HectorM14** [comment]
If calendar versioning is easier, maybe that's a good starting point. And if that ended up being too slow a release cycle, maybe switch to Hypothesis style. So in the meantime, PRs proceed as they have been until now?

**Comment by ericmjl** [comment]
Yeah, let's keep PRs coming. One of the nice things about git workflow ("gitflow") is that we can always rebase our branches on dev.

It's dawning upon me that automatic changelogs and automatic releases are kind of difficult - mostly because they involve commit history. I'm not quite sure how to deal with this in a way that is reasonable. 

One way I've been thinking of is this:

1. The usual Azure Pipeline performs all test checking that are triggered by PRs into `dev`. Let's call this pipeline `pr-checks`.
    1. We require that a `release.yaml` file is present. Here, it is only checked for being present, but not touched.
1. Upon any change triggered to `dev`, a special Pipeline builds the change log and performs a release. Let's call this pipeline `release`. 
    1. If there is a `release.yaml` file present, then:
        1. change log is updated using the `release.yaml` file, and version is bumped. Release type (one of `major|minor|patch`) is specified.
        1. `release.yaml` gets deleted.
        1. A new release is cut.
        1. After version bumping and changelog updates, we push directly back into `dev` the changes.
    1. If there is no `release.yaml` file, then nothing happens.

I'm testing these ideas in a completely disposable, private, toy repository that is also up on Azure. Will report back on whether it works!

**Comment by HectorM14** [comment]
I have no prior knowledge in this area. Is this self-directed, or are you following a guide or Hypothesis's setup?

**Comment by ericmjl** [comment]
I'm self-directed right now! Still learning, trying mostly to follow Hypothesis' setup right now, but the thing I've done on that private repo is starting to look like a mess XD.

I think the easiest thing to do currently is to ask for changelog updates on each PR, and have the CI system do an unconditional upload (ignoring existing versions) each time. Whenever a version change happens (manually), we get the uploads happening for free. Zac Hatfield-Dodds, one of the maintainers of Hypothesis, does this for another project that he's a maintainer of.
