### ISSUE TITLE
[ENH] Shuffle

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#371]
Dataframe shuffling of rows is done by an unintuitive syntax:

```python
df.sample(frac=1)
```

I propose adding a `shuffle` method:

```python
df.shuffle()
```

This should just wrap `df.sample(frac=1)`, and would be considered super-sugary syntax for the dataframe operation. I also think `shuffle` is a more intuitive name than `sample(frac=1)`. Thoughts here?

**Comment by szuckerman** [comment]
I think that's a good idea, but I think that we should be including all the arguments from the aliased function if people want to override defaults.

For example, I can imagine people would want to be able to set `random_state` when running `df.shuffle()`.
