### ISSUE TITLE
[ENH] apply_join

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#372]
An `apply_join` or `join_apply` (cannot find a better name) would be nice.

It would wrap the following `pandas` code, which I already implemented, but just haven't had the time to put into the library:

```python
@pf.register_dataframe_method
def join_apply(df, func, new_name):
    """
    Join the result of applying a function across dataframe rows.
    
    :param df: A pandas DataFrame
    :param func: A function that is applied across all rows of the
        DataFrame.
    :param new_name: New column name.
    """
    df = (
        df.copy()
        .join(
            df.apply(func, axis=1)
            .rename(new_name)
        )
    )
    return df
```

Thoughts on:

- a better name?
- usefulness?

**Comment by szuckerman** [comment]
If you apply a function to all the rows, are they "reduced" somehow? Is this like adding another column? Or could there be multiple columns?

**Comment by ericmjl** [comment]
The use case here is that I want to take information from two or more columns to create a new column.

In this case, I would want to join back the result, i.e. the new `pd.Series` that results from the `apply` line.

**Comment by zbarry** [comment]
Man I've been wanting this for the longest time.
