### ISSUE TITLE
[ENH] Inflation Adjustment

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#384]
# Brief Description

Adding inflation adjustment would be a nice addition to the `finance` tools in `pyjanitor`. The package already has an external API it uses for currency conversion, so adding another external API wouldn't be totally unreasonable.

[StatBureau](https://www.statbureau.org/en/inflation-api) provides an Inflation API, but it requires non-commercial use. There is probably something out there we can use.

Is there interest in adding this to `pyjanitor`, and is anyone eager to try implementing it?

# Example API

```python
# inflation adjust currency given currency name and years
df.adjust_inflation(column_name=['USD_2018'],
                    currency='USD',
                    reference_year=1967,
                    current_year=2018,
                    new_column_name=['USD_1967'])

```

**Comment by rahosbach** [comment]
It looks like the World Bank's API could be used. The API is URL-based and doesn't require any API keys.  If you had the country and reference and current years, you could grab the values out of the XML at a URL like the following:
https://api.worldbank.org/v2/country/USA/indicator/FP.CPI.TOTL.ZG?date=2000:2001

Note that "USA" can be replaced with any desired country, "FP.CPI.TOTL.ZG" is the World Bank's indicator code for annual % inflation based on consumer prices, and "date=2000:2001" specifies that we want the inflation values for 2000 and 2001 (these years would be replaced by the reference and current years in the method call).

If that sounds like a reasonable approach, I'll try to find some time in the next couple of days to mock up the method.

**Comment by hectormz** [comment]
Great find! And it appears to have a Creative Commons Attribution 4.0 (CC-BY 4.0) license, so everyone should be fine to use it. 

Looking forward to what you come up with!
