### ISSUE TITLE
[ENH] Send row or column to an arbitrary position in the sequence of rows/columns

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#387]
# Brief Description

I would like to propose a new function that moves a row (or column) that a user picks to a new position in the sequence of rows/columns.

cc: @bhallaY: Can you fill out an example API?

**Comment by zbarry** [comment]
This could probably be extended to multiple rows trivially, I'm thinking.

**Comment by asearfos** [comment]
I would like to work on this.
