### ISSUE TITLE
Communication Channel during SciPy 2019 Sprints

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#393]
@HectorM14 and @szuckerman, for SciPy 2019, if either of you have time to join in (9a-6p, CDT) at any point (doesn't have to be for the full time), please do so! (But no pressure!)

The primary communication channel will be by our GitHub issue tracker. 

If you do choose to join in, please feel free to make yourselves available through the way you feel most comfortable (text-based only, video/audio call, etc.). 

Let me know if you have any questions!

**Comment by szuckerman** [comment]
@ericmjl Great! I'd love to help. I should have some time to pop in and would like the idea of a video call. How would that be best accomplished?

**Comment by ericmjl** [comment]
Thanks @szuckerman! We can take either my iPad or laptop (maybe iPad, then), and keep it on Hangouts with me, I guess.

**Comment by HectorM14** [comment]
I'm looking forward to what comes out of the sprints! I likely won't be able to do any video, but should be able to pop in via Issues or email throughout the day!

**Comment by HectorM14** [comment]
It's great to see the new Issues and PRs!
