### ISSUE TITLE
[DOC] update contributors page making links consistent

### ISSUE THREAD

**Issue by asearfos** [ericmjl/pyjanitor#398]
# Brief Description of Fix
Currently, on the contributors page, the links to authors are not consistent; some go to the contributions to the repos, others go to the contributor's profile. 

I propose to make all current links go to the contributor's profile and to add additional links to each author's contributions to pyjanitor. 

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/authors.html)

**Comment by sallyhong** [comment]
Let me know if you'd like to work on this!

**Comment by asearfos** [comment]
Yes, almost done!

----
Abigail Searfoss
