### ISSUE TITLE
[DOC] Typo with back-ticks in documentation found

### ISSUE THREAD

**Issue by loganthomas** [ericmjl/pyjanitor#401]
# Brief Description of Fix
Found a "back-tick" error on a page within the pyjanitor docs. I assume this should appear as `pyjanitor` and `pandas` rather than the below image shows.

<img width="675" alt="Screen Shot 2019-07-13 at 10 43 34" src="https://user-images.githubusercontent.com/24984410/61173610-37e6f280-a55b-11e9-94a7-76a0b789269e.png">

Currently, the docs don't render backticks as code correctly.

I would like to propose a change, such that now the docs use backticks correctly.

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/notebooks/pyjanitor_intro.html#Some-things-that-are-different)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/examples/notebooks/pyjanitor_intro.ipynb)

**Comment by loganthomas** [comment]
I will be fixing this issue and looking for others as well.

**Comment by sallyhong** [comment]
You are correct. Thank you!

**Comment by loganthomas** [comment]
@kulini Contributed a commit as well with the dirty data set explanation :)
