### ISSUE TITLE
[DOC] Add a link to the Contributing.html  page in the Readme.rst

### ISSUE THREAD

**Issue by suchetaBan** [ericmjl/pyjanitor#403]
Currently, it is not very easy  for a contributor looking for setup instructions to find the contributing.html via the readme .

I would like to propose adding a link to the Contributing.html file in the readme.rst under "Contributing"

I would like to work on this fix.

(https://github.com/ericmjl/pyjanitor/README.rst)

**Comment by sallyhong** [comment]
Totally agree that the setup instructions could use more help :D 
Could you explain in more detail what the link would contain?

**Comment by suchetaBan** [comment]
i would just add a hyperlink to -
https://pyjanitor.readthedocs.io/contributing.html#

**Comment by sallyhong** [comment]
Ok! Sounds good! marking this as "being worked on"

**Comment by ericmjl** [comment]
@suchetaBan, wanted to check in with you on this. Would you like to submit a PR with your contribution to the README? If so, do let us know via this issue tracker! If not, no worries - I'll just release the issue back into the pool of issues that are "available for hacking".

**Comment by suchetaBan** [comment]
Hi Eric,
Apologize for the delay but i have had not time to look into that Issue
after returning from SciPy. Please go ahead and release the issue back into
the available for hack pool.

Thanks.
Sucheta

**Comment by ericmjl** [comment]
Thanks @suchetaBan!

**Comment by eyaltrabelsi** [comment]
@ericmjl can I work on it?
