### ISSUE TITLE
[DOC] Make semantic line break edits to documentation rst files

### ISSUE THREAD

**Issue by shandou** [ericmjl/pyjanitor#404]
# Brief Description of Fix

Currently, the docs' raw rst files do not always follow the principles of [__Semantic Line Break__](https://sembr.org/) for various markup format. This potentially weakens the readability of the rsf files both for current and future contributors.

I would like to propose a change, such that now the docs follow the Semantic Line Break principles.

# Relevant Context

- [Link to documentation page](http://pyjanitor.readthedocs.io)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/README.rst)

**Comment by shandou** [comment]
I'd be happy to work on this during the Scipy2019 Saturday sprints :)

**Comment by sallyhong** [comment]
Assigned! :D
