### ISSUE TITLE
Reword run-on sentence and fix inconsistent pronoun use

### ISSUE THREAD

**Issue by dwgoltra** [ericmjl/pyjanitor#406]
# Brief Description of Fix

In the 4th paragraph of the "Why Janitor?", there is an inconsistent "I" pronoun being used. Everywhere else in the documentation, we use "we". Additionally, this paragraph is a wordy, run on sentence this is a little difficult to read. 

I propose changing this "I" to "We" and rewriting the paragraph to improve its readability. 

- [Link to documentation page](http://pyjanitor.readthedocs.io)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/CONTRIBUTING.rst)

**Comment by sallyhong** [comment]
Would you like to work on this?

**Comment by dwgoltra** [comment]
Hi there, 

Currently,  shandou and I are working on it in this PR #424.

**Comment by jk3587** [comment]
#424 resolves this issue.
