### ISSUE TITLE
[DOC] pep8 style fix for code examples

### ISSUE THREAD

**Issue by nickdelgrosso** [ericmjl/pyjanitor#415]
# Brief Description of Fix

Right now, some of the code examples don't fit the python style guide.  I'd like to change them to match, ideally automatically with flake8 but for now just manually.

# Relevant Context
At [the board game example]( http://localhost:63342/pyjanitor/docs/_build/html/notebooks/board_games.html#Check-to-see-what-percentage-of-the-values-in-the-%E2%80%9Ccompilation%E2%80%9D-column-are-not-null)

Before:
```python
len(df[df['compilation'].notnull()])/len(df)
```

After:
```python
len(df[df['compilation'].notnull()]) / len(df)
```

- [Link to documentation page](http://pyjanitor.readthedocs.io)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/AUTHORS.rst)

**Comment by sallyhong** [comment]
Let me know if you'd like to work on this! :D

**Comment by nickdelgrosso** [comment]
Yes!

Added #429

**Comment by ericmjl** [comment]
Hi @nickdelgrosso! Don't want to put pressure on you, but I just wanted to check-in to see if you're still working on this issue or not. If not, no worries! I'll release the issue back into the "available for hacking" pool. 

Hope you've been having a good time post-sprints!

**Comment by nickdelgrosso** [comment]
Hi, sorry but I'm not in it anymore.

Best wishes,

Nick
