### ISSUE TITLE
Add link to TidyTuesday examples point to Tidy Data paper

### ISSUE THREAD

**Issue by cjmayers** [ericmjl/pyjanitor#422]
I would like to add text and a link to the end of the first paragraph on the first [TidyTuesday example](https://pyjanitor.readthedocs.io/notebooks/tidytuesday_20190423.html) that would point to Hadley Wickham's Tidy Data paper.

Before:
We will use pyjanitor to showcase how to conveniently chain methods together to perform data cleaning in one shot. The below example shows a one-shot script followed by a step-by-step detail of each part of the method chain.

Addition would include the following:

Note: TidyTuesday is based on the principles discussed and made popular by Hadley Wickham in his paper [Tidy Data](https://www.jstatsoft.org/index.php/jss/article/view/v059i10/v59i10.pdf).

I would be interested in working on this.

**Comment by benjaminjack** [comment]
We have a pull request open that modifies the TidyTuesday examples. You may want to wait until those are merged before making any changes.

**Comment by benjaminjack** [comment]
The other pull request was merged, so feel free to pull and work on this now.
