### ISSUE TITLE
[DOC] Columns are misaligned in the table on "API Documentation" page

### ISSUE THREAD

**Issue by DSNortsev** [ericmjl/pyjanitor#426]
Currently, columns in the table are misaligned on "API Documentation" page

<img width="737" alt="2019-07-13_1322" src="https://user-images.githubusercontent.com/16304028/61175288-78b72980-a5a4-11e9-814d-38ee95b7a8a2.png">

**Comment by DSNortsev** [comment]
I would like to work on that issue

**Comment by jk3587** [comment]
#428 resolves this issue
