### ISSUE TITLE
[DOC] Broken link on encode_categorical function

### ISSUE THREAD

**Issue by gaworecki5** [ericmjl/pyjanitor#440]
# Brief Description of Fix

Before -  the link below is broken
<http://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html> # noqa: E501 dtype.

After - correct working link to the pandas documentation

[Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html)

Link to documentation page"
- [link to page to be edited](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.encode_categorical.html#janitor.encode_categorical)

**Comment by sallyhong** [comment]
Great catch!
