### ISSUE TITLE
[DOC] Adding context about method chaining  

### ISSUE THREAD

**Issue by aopisco** [ericmjl/pyjanitor#446]
# Brief Description of Fix

Currently, the docs don't explain what method chaining is. A beginner would benefit from reading about it.

I would like to propose a change, such that now the docs include a link to a medium post explaining the topic.

# Relevant Context

- [Link to documentation page](http://pyjanitor.readthedocs.io)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/README.rst)

**Comment by ericmjl** [comment]
This is being worked on by @aopisco.
