### ISSUE TITLE
[DOC] API Documentation for Chemistry functions is not standardized

### ISSUE THREAD

**Issue by loganthomas** [ericmjl/pyjanitor#462]
# Brief Description of Fix

Currently, the docs do not have a standard docstring format for functions. Some docstrings contain only `Parameters`. Some have `Parameters` and `Method chaining usage`.  Some have a combination of `Parameters`, ` Returns`, `Functional usage example`, and `Method chaining example` but not each one of these pieces.

I would like to propose a change, such that now the docs contain a **standardized** docstring suite. All functions should contain (at a minimum) the following:
  - `Parameters`
  - ` Returns`
  - `Functional usage example`
  - `Method chaining example`

**NOTE**: This can be done for all functions within the `janitor` directory. For ease of review, this will focus on the `chemistry.py` file and move to other files/functions as time permits.

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/reference/chemistry.html)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/chemistry.py)

**Comment by loganthomas** [comment]
I would like to work on this issue :) Yah docstrings!

**Comment by loganthomas** [comment]
@ericmjl 

Currently working on the docstrings for functions within the chemistry.py file. I'm wondering what your preferred docstring example format would be. See below for an example:

## Current Docs
<img width="614" alt="Screen Shot 2019-07-14 at 15 29 41" src="https://user-images.githubusercontent.com/24984410/61188959-39dcae80-a64c-11e9-987b-6967b8c0f003.png">


## Suggestion
<img width="634" alt="Screen Shot 2019-07-14 at 15 27 34" src="https://user-images.githubusercontent.com/24984410/61188946-187bc280-a64c-11e9-9352-9adf6ce04ac7.png">

I think the suggestion does 2 things better than the current docs:

(1) It reminds the user that the df must be in *mols* (i.e. a result of calling `.smiles2mol()` **prior** to calling `.maccs_keys_fingerprint()`)

(2) It shows a better example of "chaining". The current docs just show one "dot" method. Including the `.smiles2mol()` call shows a better "chaining" example.

Open to suggestions. Would love to know your preference before converting all the functions within `chemistry.py`.

Thanks!

**Comment by ericmjl** [comment]
Thanks for the ideas, @loganthomas! I think the suggestion is great, let’s go with it!
