### ISSUE TITLE
[DOC] Add workaround for bug #464 building docs using "make html" - windows only 

### ISSUE THREAD

**Issue by cjmayers** [ericmjl/pyjanitor#465]
# Brief Description of Fix

Currently, the docs does not cover a workaround for bug #464 and this prevents windows users from building the html documents. 

I would like to propose a change, such that the docs would include the current workaround discussed in bug #464 where a junction is created. 

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/contributing.html)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/CONTRIBUTING.rst)

I would like to work on this.

**Comment by ericmjl** [comment]
Closed by #466.
