### ISSUE TITLE
[DOC] International Teacher Data notebook should not have 1st-level markdown beyond title

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#476]
# Brief Description of Fix

Currently, the example on [Processing International Teacher data](https://pyjanitor.readthedocs.io/notebooks/teacher_pupil.html) has two top-level markdown titles: One for `Processing International Teacher Data`, and the other for `Data Dictionary`. 

I would like to propose a change, such that `Data Dictionary` gets demoted to 2nd level. This would prevent it from showing up on the navigation tab of the docs.

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/notebooks/teacher_pupil.html#Data-Dictionary)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/examples/notebooks/teacher_pupil.ipynb)

**Comment by jk3587** [comment]
I'll fix this.
