### ISSUE TITLE
[ENH] deconcatenate_column to preserve the original column location

### ISSUE THREAD

**Issue by shandou** [ericmjl/pyjanitor#478]
# Brief Description

I would like to propose an enhancement to `deconcatenate_column` for preserving the original column position.

The current implementation will append the deconcatenated columns to the right of the original dataframe. In this way, the relative positions of the columns are not preserved.

I'd like to have a boolean kwarg that allows users to preserve the original column order.

# Example API
```python
df = (pd.DataFrame(...).
      deconcatenate_column(..., preserve_position=True)
```

**Comment by shandou** [comment]
Also, the examples in documentation uses plural, even though the function itself uses singular form (`deconcatenate_column`):
```python
df = deconcatenate_columns(df,
                           column_name='id',
                           new_column_names=['col1', 'col2'],
                           sep='-')
```

**Comment by shandou** [comment]
I can work on the enhancement and documents correction once I am done with the example notebook.

**Comment by ericmjl** [comment]
Thanks @shandou for picking out the doc inconsistency, and for proposing the new kwarg! Yes, definitely this would be a good PR to make. I will mark this as taken.

As a heads-up, more verbose docstrings on what `preserve_position` does, including a mini-example of some kind, would be very helpful. I would not skimp on text here; oftentimes there’s more lines of docstrings than implementation :smile:
