### ISSUE TITLE
Feature thought - chainable, in place reset_index 

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#48]
As far as I'm aware, an `inplace=True` `reset_index()` does not return a `DataFrame`.

**Comment by ericmjl** [comment]
@zbarry hmm... gotta think about this. I think `reset_index()` without `inplace=True` is meant to be part of a method chain, as `reset_index()` returns a DataFrame.

**Comment by zbarry** [comment]
I believe `reset_index()` copies the data:

```python
df = pd.DataFrame({'x': np.arange(0, 10)})

df2 = df.reset_index(drop=True)

print('before:')

display(df)
display(df2)

df2.iloc[0, 0] = 1

print('after:')

display(df)
display(df2)
```

`df2` is modified, but `df` is not.

**Comment by zbarry** [comment]
Thinking just a little bit about this, I feel like if such a feature were to be implemented, it would have to be named something completely different instead of changing the fundamental behavior of `reset_index()`. I don't have enough experience with pandas, though, to know what an intuitive name would even be.

**Comment by zbarry** [comment]
Proposal to just name it `inplace_reset_index()` and clearly explain the logic of why this exists in the docstring.
