### ISSUE TITLE
[DOC] Authors page should reflect more than git commit contributions

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#483]
# Brief Description of Fix

Currently, the docs only link to code contributions that involve a `git commit`. This does not reflect the contributions made by others to the project, such as talks, helping with sprints, social media, and more. 

I would like to propose a change, such that now the docs includes at least code sprint contributions. For example, @jk3587 and @sallyhong helped with issues and guiding others at the last sprint at SciPy 2019, @loganthomas and @jekwatt helped others with `git` at SciPy and PyCon respectively. 

# Relevant Context

- Link to documentation page: [Contributors](https://pyjanitor.readthedocs.io/authors.html)
- File to be edited: https://github.com/ericmjl/pyjanitor/blob/dev/AUTHORS.rst

**Comment by jekwatt** [comment]
If the link to `File to be edited` does not work, try this:
https://github.com/ericmjl/pyjanitor/blob/dev/AUTHORS.rst

**Comment by hectormz** [comment]
How can they be properly recognized on `Authors.rst`? 

Including when and how they contributed and guided others? 

A tree graph of guidance?

**Comment by ericmjl** [comment]
I think bullet points indicating non-coding contributions would be a way out.

**Comment by hectormz** [comment]
Is this now closed by #491 ?

**Comment by ericmjl** [comment]
Yes, indeed, thanks for pointing this out, @hectormz!
