### ISSUE TITLE
[ENH] Unit Conversion

### ISSUE THREAD

**Issue by rahosbach** [ericmjl/pyjanitor#486]
# Brief Description

I would like to propose a set of `engineering` methods that would convert units (e.g., Fahrenheit to Celsius, or Pascals to mmHg, etc.) as well as prefixes (e.g., milligrams to kilograms, kWh to MWh, etc.).

This could go down a big rabbit hole.  But maybe we could rely on [Pint](https://pint.readthedocs.io/en/0.9/), or a similar package.

# Example API

```python
# Convert a column of temperatures in Celsius to Fahrenheit
df.convert_units(column_name='temperature_c',
                 existing_units='C',
                 to_units='F',
                 create_new_column=False)
```

**Comment by jcmkk3** [comment]
I don’t know how they compare, but it might be worth evaluating [unyt](https://unyt.readthedocs.io/en/stable/) as well.

**Comment by ericmjl** [comment]
This is a great idea! I will suggest the following API change, though, to match it more closely to the `transform_column` API:

```python
# Convert a column of temperatures in Celsius to Fahrenheit
df.convert_units(
    column_name='temperature_c',
    existing_units='C',
    to_units='F',
    dest_column_name=None)
```

Suggesting this change only because it semantically is of the same idea as `transform_column`, so it's nice to keep these semantically-similar functions together.

**Comment by rahosbach** [comment]
After looking at pint and unyt, unyt appears to potentially be a better choice.  It definitely has more recent development, but its use will require sympy (as well as unyt itself, of course).

I would like to work on incorporating this convert_units() method.

**Comment by ericmjl** [comment]
Awesome stuff, thanks @rahosbach! Looking forward to your PRs :smile:. I'll mark this as "being hacked on".
