### ISSUE TITLE
[DOC] transform_column dest_column_name kwarg description needs to be clearer on defaults

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#487]
# Brief Description of Fix

The current wording on `dest_column_name` is:

`dest_column_name – The column name to store the transformation result in. By default, replaces contents of original column.`

I would like to propose to change it to:

`dest_column_name – The column name to store the transformation result in. Defaults to None, which will result in the original column name being overwritten. If a name is provided here, then a new column with the transformed values will be created.`

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.transform_column.html)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/functions.py#L2034)

**Comment by evan-anderson** [comment]
It looks like this issue is still open - I'd be happy to take care of it!

**Comment by ericmjl** [comment]
@evan-anderson I'm happy to assign it to you! :smile: Hope you've been having fun!
