### ISSUE TITLE
[DOC] Docstring style should be made clear in `contributing` page

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#488]
# Brief Description of Fix

Currently, the docs do not clearly describe the coding standards that the project probably should adhere to.

I believe this should be added to the `Contributing` page. 

For reference, it should look something like this:

<hr>

We recommend that you write docstrings before you write a test for the function, and that you write the test before writing the function implementation. This is an example of combining doc- and test-driven development together, to clarify what the function is intended to do before actually implementing it. Use the following example to help guide you on how to write your new function docstring properly.

```python
def new_janitor_function(df, param1, param2):
    “””
    One line that describes what the function does.

    Further elaboration on the function. Use one or more paragraphs to do any of the following:
    1. Provide more detail on intended usage
    2. Clearly state assumptions on what the input dataframe should look like.
    3. Identify edge cases that will cause the function to raise an error.
    4. Other things that you want the end-user to know about before using the function.

    Method chaining example:

    .. code-block:: python

        df = df.new_janitor_function(param1, param2)

    Functional example:

    .. code-block:: python

        df = new_janitor_function(df, param1, param2)

    :param param1: A description of param1.
    :param param2: A description of param2.
    :return: A description of the dataframe that is returned.
    “””
    # now put your function implementation here
```

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/contributing.html#pull-request-guidelines)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/CONTRIBUTING.rst)

**Comment by shandou** [comment]
@ericmjl I can work on this issue.

**Comment by ericmjl** [comment]
Ok! Thanks @shandou, I will leave it in your hands then :smile:.

**Comment by hectormz** [comment]
This is adjacent to #357, can they be combined?

**Comment by shandou** [comment]
@hectormz I like that issue as well and I had the exact same questions on Friday when trying to extend a function feature (for example, it was not very clear to me at first about where the test data was loaded). If you and @ericmjl are both comfortable with me taking a stab at it, please combine the two issues.
Can't guarantee to get the skeleton examples right at first try, but I am sure you guys can help me iterate.

**Comment by shandou** [comment]
@ericmjl I am adding instructions about unit tests but not very certain about the use of custom marks in this particular example:

```python
@pytest.mark.functions
@pytest.mark.test
def test_shuffle(dataframe):
    """
    Test the shuffle function.

    This test checks that the set of indices in the shuffled dataframe are
    identical to the set of indices in the original.
    """
    df = dataframe.shuffle()

    assert set(df.index) == set(dataframe.index)
```
Just to double-check with you:
My understanding is that having `@pytest.mark.function` decorator allows us to cherry-pick a subset of tests we want to run. 

For example:
```bash
# Run all the tests marked with `@pytest.mark.functions`
$ pytest -v -m functions

# Run all the tests except the ones marked with `@pytest.mark.functions`
$ pytest -v -m 'not functions'
```

But it is not clear to me as to ___what we are doing with the additional mark @pytest.mark.test___. When you have a chance, could you help me better understand this? Thanks a lot!! 😃

**Comment by shandou** [comment]
Also, I can see `mypy` as one of the dependencies, but I don't see explicit use of it in the repo. Curious about whether type checker is used during CI? And how? Thanks!

**Comment by ericmjl** [comment]
@shandou you caught a bug of mine!

> what we are doing with the additional mark @pytest.mark.test

I used to use it to isolate just the test that I'm currently hacking on. It must have slipped into the library. 

The correct way to isolate _just the test that we are writing_, borrowing the example above, is to do:

```bash
$ pytest -k test_shuffle
```

This will run only the tests that contain the substring `test_shuffle`. Usually that is good enough to avoid running the full test suite.

> Also, I can see mypy as one of the dependencies, but I don't see explicit use of it in the repo. Curious about whether type checker is used during CI? And how? Thanks!

`mypy` is used during development. I have a PR open to use `mypy` in CI, but I'm still not clear what we'd be checking for though. I think we can ignore `mypy` for the time being.
