### ISSUE TITLE
Reminder of add_columns implementation

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#49]
For myself, mostly:

Chaining implementation:

```python
import pandas_flavor as pf

@pf.register_dataframe_method
def add_columns(df, **kwargs):
    # column already exists
    # v is not a scalar but is a different length from the dataframe
    
    for k, v in kwargs.items():
        df = df.add_column(k, v)
    return df
```
Example usage for copying repeating rows from a `DataFrame` into another:

`df1.columns` is of `{'var1', 'var2', 'var3'}`

```python
column_order = ['var1', 'var2']

df2.add_columns(**{
    col: vals
    for col, vals in zip(column_order, df1[column_order].iloc[0]) 
})
```

**Comment by ericmjl** [comment]
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.assign.html

It appears add_columns can simply function as a syntactic sugar wrapper for assign. Fulfills the goal of a cleaner or more explicit API.

**Comment by zbarry** [comment]
We should confirm `assign` doesn't copy the underlying data.

**Comment by zbarry** [comment]
`assign` indeed copies the underlying data:

![image](https://user-images.githubusercontent.com/4762711/48662979-bab0bf80-ea57-11e8-95ae-6ae108cd15e0.png)

*shrug*.

I'll move forward with the implementation we came up with.

**Comment by zbarry** [comment]
🥇
