### ISSUE TITLE
[TST] test_deconcatenate_column tests should be consolidated together

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#492]
This is in reference to the last PR by @shandou (#484). I let the two separate tests go to not hold up the PR, but we should put the two separate tests together.

Relevant context:

- Contents of [this file](https://github.com/ericmjl/pyjanitor/blob/dev/tests/functions/test_deconcatenate_column_preserve_position.py) should be moved into [`test_deconcatenate_column.py`](https://github.com/ericmjl/pyjanitor/blob/dev/tests/functions/test_deconcatenate_column.py)

**Comment by shandou** [comment]
Sorry, my bad! As the culprit, I'll take this issue @ericmjl and have it fixed :P

**Comment by ericmjl** [comment]
@shandou don’t worry about it - I have already put in the PR for this!

**Comment by ericmjl** [comment]
Closed by #492.
