### ISSUE TITLE
[DOC] Clarify Python version requirements

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#493]
# Brief Description of Fix

I was looking through documentation (for users and contributors), and it was unclear to me which python versions we actually support. It seems that we support python 3.6 + 3.7. This arose as I was updating the `pyproject.toml` file to avoid the warning:
```
--py36 is deprecated and will be removed in a future version. Use --target-version py36 instead.
```

Our current locations of explicit python versions are in:
- `pyproject.toml`
    - `py36 = true`
- `environment-dev.yml`
    - `- python >= 3.6`
- `.azure-pipelines/pipeline-master.yml`
    - `python.version: "3.7"`

# Proposed Fix

If `pyjanitor` is in fact meant to function on 3.6+, we should
- Explicitly inform contributors that their code should be 3.6+ compatible
- Inform users which python versions the package requires, on the documentation site, PyPI etc
- Add `python_requires=">=3.6"` to `setup.py`

**Comment by ericmjl** [comment]
Thanks for the catch, @hectormz! 

I think we only test on the latest version of Python, which means that is the only “officially” supported version. (I disabled 3.6, to allow more CI pipelines to run simultaneously.)

That said, we do use language features that only show up in Python 3.6 onwards, I think.

Let’s definitely move forward with what you suggested.

**Comment by hectormz** [comment]
Great, I'll make some changes to establish in documentation and code that this supports Python 3.6+ and submit a PR
