### ISSUE TITLE
[DOC] PyPI page has no project description

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#495]
# Brief Description of Fix

The PyPI page for `pyjanitor` has no project description. I'm not sure if it previously did, and was lost in a recent version update. I'm not sure how to fix it, but I assume it's something that @ericmjl would be able to change. 

# Relevant Context
- [Link to PyPI page](https://pypi.org/project/pyjanitor/)

**Comment by ericmjl** [comment]
Turns out, this is something that can be done via PR! 

https://packaging.python.org/guides/making-a-pypi-friendly-readme/

In other words, I’m not necessarily the bottleneck here 😉. 

Jokes aside, I’d be happy to let this one be handled by another person if they’d like to do it, but no pressure. For someone who is looking for information, I _think_ the GitHub repository is higher-ranked on Google than the PyPI page. That said, it’d be super nice to have the PyPI page rendered nicely too :smile:.

**Comment by hectormz** [comment]
Awesome! It's a nice chance to understand some more of the packaging process too.

**Comment by hectormz** [comment]
What do we want to include in the PyPI description? I tested, and we could simply link the entirety of the current `README.rst` if we wanted. Or we could use a shorter description, specifically, the start of the `README.rst` (with formatting):

> pyjanitor is a Python implementation of the R package janitor, and provides a clean API for cleaning data.
> Why janitor?
> 
> Originally a port of the R package, pyjanitor has evolved from a set of convenient data cleaning routines into an experiment with the method chaining paradigm.
> 
> Data preprocessing usually consists of a series of steps that involve transforming raw data into an understandable/usable format. These series of steps need to be run in a certain sequence to achieve success. We take a base data file as the starting point, and perform actions on it, such as removing null/empty rows, replacing them with other values, adding/renaming/removing columns of data, filtering rows and others. More formally, these steps along with their relationships and dependencies are commonly referred to as a Directed Acyclic Graph (DAG).
> 
> The pandas API has been invaluable for the Python data science ecosystem, and implements method chaining of a subset of methods as part of the API. For example, resetting indexes (.reset_index()), dropping null values (.dropna()), and more, are accomplished via the appropriate pd.DataFrame method calls.
> 
> Inspired by the ease-of-use and expressiveness of the dplyr package of the R statistical language ecosystem, we have evolved pyjanitor into a language for expressing the data processing DAG for pandas users.
> 
I am leaning more towards the truncated version.


The test is temporarily at <https://test.pypi.org/project/pyjanitor/>

**Comment by ericmjl** [comment]
I have no strong opinions - let's go with what you suggested, @hectormz!
