### ISSUE TITLE
[ENH] Allow substring and regex matching in find_replace

### ISSUE THREAD

**Issue by shandou** [ericmjl/pyjanitor#496]
# Brief Description

Currently `find_replace` only allows exact matching. I have run into use cases for fuzzy/substring match and replace both in my work and in the process of making a pyjanitor example. Was able to implement it by combining pyjanitor function `update_where` and pandas-flavor, but we potentially could make this as a pyjanitor feature--either as part of `find_replace` (for example, by adding a kwarg flag `exact=True/False`), or as a separate function `fuzzy_find_replace`.

# Example API

For example, in the example [Tidy Up Web-Scraped Media Franchise Data](https://pyjanitor.readthedocs.io/notebooks/medium_franchise.html), when trying to implement a python equivalence of the following R snippet:
```R
clean_df <- clean_category %>%
  mutate(revenue_category = case_when(
    str_detect(str_to_lower(revenue_category), "box office") ~ "Box Office",
    str_detect(str_to_lower(revenue_category), "dvd|blu|vhs|home video|video rentals|video sales|streaming|home entertainment") ~ "Home Video/Entertainment",
    str_detect(str_to_lower(revenue_category), "video game|computer game|mobile game|console|game|pachinko|pet|card") ~ "Video Games/Games",
    str_detect(str_to_lower(revenue_category), "comic|manga") ~ "Comic or Manga",
    str_detect(str_to_lower(revenue_category), "music|soundtrack") ~ "Music",
    str_detect(str_to_lower(revenue_category), "tv") ~ "TV",
    str_detect(str_to_lower(revenue_category), "merchandise|licens|mall|stage|retail") ~ "Merchandise, Licensing & Retail",
    TRUE ~ revenue_category))
```
A mapper dictionary could be set up as:
```python
mapper = {
    'box office': 'Box Office',
    'dvd|blu|vhs|home video|video rentals|video sales|streaming|home entertainment': 'Home Video/Entertainment',
    'video game|computer game|mobile game|console|game|pachinko|pet|card': 'Video Games/Games',
    'comic|manga': 'Comic or Manga',
    'music|soundtrac': 'Music',
    'tv': 'TV',
    'merchandise|licens|mall|stage|retail': 'Merchandise, Licensing & Retail',
}
```

If we enable substring matching and regex, the find_replace call could look like this:
```python
df.find_replace(column_name, mapper, exact=False, regex=True)
```

If this feature extension could clutter `find_replace`, a separate function could be set up.

**Comment by ericmjl** [comment]
This is a great idea, @shandou! I think the API could be simplified by using strings. An example might be:

```python
# One of the following
df.find_replace(df, column_name, mapper, match=‘exact’)
df.find_replace(df, column_name, mapper, match=‘regex’)
```

If we default to ‘exact’, this preserves the current behaviour, and we can add in a ‘regex’ string as an option as well.

**Comment by shandou** [comment]
Don't want to overpromise, but I can take this issue as well and get onto it once I am done with the `contribution.rst` improvements--only if no one else wants to claim it of course 😄

**Comment by ericmjl** [comment]
Alright! I will keep it open and available for others until you officially claim it for yourself. :smile:

**Comment by shandou** [comment]
@ericmjl Okay I officially claim this issue 😃
