### ISSUE TITLE
[ENH] Add optional removal of accents on functions.clean_names, enabled by default.

### ISSUE THREAD

**Issue by mralbu** [ericmjl/pyjanitor#502]
# Brief Description

I'd like to suggest an option to remove accents from column names on the clean_names function.
It could be implemented using the normalize function of the standard library unicodedata:

[What is the best way to remove accents in a Python unicode string?](https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string)

I have created a branch called strip_accents and checked that the code addition does not break any tests.
[mralbu/pyjanitor/tree/strip_accents](https://github.com/mralbu/pyjanitor/tree/strip_accents)

# Example API

```python
# create test DataFrame
df = pd.DataFrame({"João": [1, 2], "Лука́ся": [1, 2], "Käfer": [1, 2]})

# remove column name accents
df = df.clean_names(strip_accents=True)
expected_columns = ["joao", "лукася", "kafer"]
assert set(df.columns) == set(expected_columns)
```

**Comment by ericmjl** [comment]
Thanks for pinging in, @mralbu!

Yes, I think this would be a great addition to the library. Would you like to submit in a PR?

**Comment by mralbu** [comment]
Thank your for the great library! I use rstats janitor, and I did miss some of its functionality in python. (particularly cleaning column names and removing accents, which the R package does by default)
I'd be happy to submit a pull request, thanks!
