### ISSUE TITLE
Welcome to Shan

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#516]
Welcome on board to the team, @shandou!

cc: @zbarry @hectormz @jk3587 @szuckerman @sallyhong 

I invited @shandou on-board for the following qualitative reasons:
- her most recent PRs were of high technical quality and very meticulously done.
- her use of pyjanitor looks complementary to the rest of us (as far as I can tell).
- she has volunteered on contributions.

Also wanted to more formally thank the rest of you for helping out with the project in ways big and small. I definitely appreciate the effort put into making the library better. 

- @jk3587 and @sallyhong, thanks for helping out with the sprints at SciPy 2019, and for being at the Sprints at PyCon; 
- @hectormz thank you for the numerous high quality improvements to the library, as well as reviews on the PRs that have come in; 
- @szuckerman you were one of the first users of the library to just jump in and start making contributions, and I was very thrilled to have you on board;
- @zbarry there’s nothing to thank here 😝 ... I jest; lots of great suggestions and ideas, and we make a great pair coding team at work!

I will be closing this issue as soon as I’ve posted it, so that it doesn’t remain on the Issue Tracker.

**Comment by hectormz** [comment]
Welcome @shandou! I'm looking forward to seeing more of your superb contributions! 🎉🎊

**Comment by zbarry** [comment]
> @zbarry there’s nothing to thank here

:(

**Comment by shandou** [comment]
Thank you all!! 😃
