### ISSUE TITLE
Update_where example refers to columns not in example df

### ISSUE THREAD

**Issue by anzelpwj** [ericmjl/pyjanitor#529]
# Brief Description of Fix

`update_where` has a nice example in its documentation, but refers to `Column A`, `B`, and `C`, which are not in the example dataframe. Let's update the documentation so that the code will work, and where we can show example output of running the code.

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.update_where.html#janitor.update_where)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/functions.py)

I'll be happy to work on this docfix, if approved.

**Comment by ericmjl** [comment]
Assigned to you, @anzelpwj! :smile:
