### ISSUE TITLE
Update the bad_values notebook to show use of update_where for fixing ranges

### ISSUE THREAD

**Issue by anzelpwj** [ericmjl/pyjanitor#530]
# Brief Description

One issue I've run into trouble with when working with data is that I need to define a range of bad values - for example, sale price should always be > 0. It looks like the `update_where` function would be a good candidate

```python
df = jn.update_where(df['price'] < 0, 'price', None)
```

but it took me a bit of time to find this function for this use-case. I'd like to add a note to the `bad_values` notebook to show the usage of this function for addressing ranges of values.

As a specific example, we could note that longitude needs to be in a range [-180, 180] and latitude is in a range of [-90, 90]. And, since this is US data, we the latitude and longitude boundaries of the USA as tighter boundaries (19.50 to 64.86 lat, -161.76 to -68.01 long). If someone was keying in the values and misplaced a decimal somewhere, this could be an easy way to catch the problem.

If this is approved, I'd be happy to submit the fix.

**Comment by ericmjl** [comment]
Thanks for raising this, @anzelpwj! Yes, I'd love to see the contribution and review it. Looking forward to reviewing!
