### ISSUE TITLE
[DOC] Move Setting up environment in PyCharm to its own page

### ISSUE THREAD

**Issue by Ram-N** [ericmjl/pyjanitor#535]
# Context: Move a section to its own page

While tinkering with the Docs, I noticed that `Contributing.html` is quite long now. So much so that it might be a bit daunting for future contributors.

Towards the tail end of that same page, I see that there is a Section (with nice Images) of how to go about setting up the `environment` for PyCharm users. 

I would like to propose that we consider moving this section to its own stand-alone page. `Contributing.html` could link to that page and direct those who are using PyCharm to go there.

There are pros and cons to having one long page versus multiple smaller pages. (For that matter, `Getting Started` could be its own page too.)  Is there any appetite for moving "Set up env in PyCharm" to be its own page? If yes, just assign it to me. Thanks.

**Comment by zbarry** [comment]
@Ram-N - sorry that this wasn't responded to. I agree that the contributing guide is a monster, and could definitely be made a bit more modular. I think this definitely applies to more than just the PyCharm portion, too! Going to assign you.

**Comment by Ram-N** [comment]
Thanks, Zachary. Will get to it soon.

**Comment by ericmjl** [comment]
Closing this issue because #594 is merged. Thanks @Ram-N for the contribution!
