### ISSUE TITLE
Welcome Paul Anzel to the team!

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#536]
I have decided to invite @anzelpwj as a collaborator on the project. He’s been active on identifying a smattering of issues that I haven’t had the bandwidth to tackle (and equally importantly, raising them on the issue tracker), and has been a great resource for other contributors. 

Welcome on board, @anzelpwj!

**Comment by anzelpwj** [comment]
Hooray, thanks for the welcome!
