### ISSUE TITLE
[ENH] Add a reset_index boolean kwarg to shuffle()

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#540]
# Brief Description

I would like to propose to add a `reset_index` boolean kwarg to the `.shuffle()` function.

Doing so would help save a line of code. After shuffling a dataframe, the index remains the same. Sometimes, users may want to preserve the index, but my current opinionated opinion is that preservation of the index might not be the 90% use case. Instead, we want to shuffle the rows without keeping each row attached to its original index, i.e. we would want to reset_index.

# Example API

We would just add the reset_index kwarg to shuffle.

```python
df.shuffle(reset_index=True)
```

Underneath the hood, it would simply call .reset_index(drop=True):

```python
def shuffle(df, ..., reset_index=True):
    ...
    ...
    if reset_index:
        df = df.reset_index(drop=True)
    return df
```

**Comment by eyaltrabelsi** [comment]
@ericmjl 
I would love to work on this
