### ISSUE TITLE
Welcome Zijie to the team!

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#544]
On the basis of his contribution to extend pyjanitor to be compatible with pyspark, I have added @zjpoh to the team. Welcome on board! 

Zijie and @anzelpwj have the most experience amongst us with pyspark, and I'm looking forward to seeing their contributions!

cc: @zbarry @szuckerman @hectormz @shandou @sallyhong @anzelpwj @jk3587

**Comment by hectormz** [comment]
Welcome!

**Comment by zjpoh** [comment]
Thanks! Looking forward to working with you guys~
