### ISSUE TITLE
[DOC] Update pandas example in the README?

### ISSUE THREAD

**Issue by TomAugspurger** [ericmjl/pyjanitor#548]
# Brief Description of Fix

Right now, the pandas example in the README shows what I (IMHO) would say is "bad" pandas code. I would rather write it as something like

```python
In [15]: df = (
    ...:    pd.DataFrame(company_sales)
    ...:     .drop(columns="Company1")
    ...:     .dropna(subset=['Company2', 'Company3'])
    ...:     .rename(columns={"Company2": "Amazon", "Company3": "Facebook"})
    ...:     .assign(Google=[450.0, 550.0, 800.0])
    ...: )
    ...: df
Out[15]:
  SalesMonth  Amazon  Facebook  Google
0        Jan   180.0     400.0   450.0
1        Feb   250.0     500.0   550.0
3      April   500.0     675.0   800.0
```

Thoughts on updating that example? I would certainly keep the current one, since it makes it clear that pandas *allows* the "bad" style, while pyjanitor doesn't. But I think it'd be nice to include the "good" style as well :)

**Comment by ericmjl** [comment]
Yes! Let's do that, @TomAugspurger! Let me mark this as a docfix and one that a newcomer can attempt.
