### ISSUE TITLE
[ENH] Decorator utility for handling NAs and errors (for transform_column)

### ISSUE THREAD

**Issue by jiafengkevinchen** [ericmjl/pyjanitor#549]
# Brief Description

If say `df["x"]` is a string column with NAs, then the routine `df["x"].apply(lambda x : x+"1")` doesn't work due to the NAs. It would be useful to have a decorator such that 
```python
df.transform_column("x", skipna(lambda x : x + "1"))
``` 
would work

# Example API

```python
from janitor.func_utils import skipna, skiperror

df.transform_column("x", skipna(lambda x : x + "1"))
df.transform_column("y", skiperror(func))

@skiperror
def foo(x):
    ...
    pass
```

# Example implementation

```python

def skipna(f):
    def _wrapped(x):
        if type(x) is float and np.isnan(x) or x is None:
            return np.nan
        else:
            return f(x)

    return _wrapped


def skiperror(f, return_val=None, return_x=False):
    def _wrapped(x):
        try:
            return f(x)
        except:
            if return_x:
                return x
            return return_val

    return _wrapped
```

**Comment by ericmjl** [comment]
@jiafengkevinchen thanks for pinging in! I think the example implementation looks great. Are you up for a PR?

**Comment by jiafengkevinchen** [comment]
Sure. I'm not sure what namespace to put these in though
Is `from janitor.func_utils import skipna, skiperror` reasonable?

**Comment by ericmjl** [comment]
@jiafengkevinchen we have a `janitor.utils`, and I think that is a reasonable first place to put it. 

I will assign it to you; looking forward to reviewing the PR! (Don’t forget tests, and to also add your contribution to the CHANGELOG :smile:)
