### ISSUE TITLE
[DOC] #noqa comment appears in docs

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#555]
# Brief Description of Fix

A `#noqa:E501` comment in the docstring from `encode_categorical()` appears in [the docs](https://pyjanitor.readthedocs.io/reference/general_functions.html#preprocessing). The `#noqa:E501` comment exists due to a long url in the docstring which angers `pycodestyle`. 

I'm currently not familiar enough with `reStructuredText` or `Sphinx` to know how to solve this issue.

A quick search of the published docs shows [a number of #noqa comments](https://pyjanitor.readthedocs.io/search.html?q=%23noqa&check_keywords=yes&area=default) that may not be desired.

# Relevant Context

- [Link to documentation page](https://pyjanitor.readthedocs.io/reference/general_functions.html#preprocessing)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/blob/dev/janitor/functions.py)

**Comment by ericmjl** [comment]
This is a great catch, @hectormz! I'm not too worried about these; the `# noqa` comments are in the docstrings, and as such they get linted. A way around them is to modify the code blocks, but that shouldn't be a big problem.

For now, I'll tag this as "needs further discussion", as I don't have strong opinions on whether they should appear in the docs or not - but I'd like this to continue to be discussed.

**Comment by hectormz** [comment]
Sure, not mission critical. Just happened to notice it, and knew it wasn't our intent to have `#noqa` leak into docs.

On a related note, it looks like the url in [remove_empty doc](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.remove_empty.html?highlight=stackoverflow#janitor-remove-empty) is formed correctly, while [convert_matlab_date](https://pyjanitor.readthedocs.io/reference/janitor.functions/janitor.convert_matlab_date.html?highlight=stack%20overflow#janitor-convert-matlab-date) is not.

That should be an easy fix

**Comment by bdice** [comment]
I had this problem in a package I maintain, and we solved it by moving `#noqa` to the line where the triple quote ends, like this:

```
"""A fancy docstring.

It'd be a shame if we ruined this beautiful docstring with a long
`StackOverflow`_ link.

.. _StackOverflow: https://stackoverflow.com/questions/38884538/python-pandas-find-all-rows-where-all-values-are-nan
"""  # noqa: E501
```

Example from my package's code: https://github.com/glotzerlab/freud/blob/0dae9cee1423ae9a0ed8923547e44c41b93b5672/freud/order.pyx#L188-L194

**Comment by hectormz** [comment]
Thanks for the suggestion @bdice it worked nicely! @ericmjl , do you agree this is a good way forward, to apply #noqa E501 to docstrings? The only drawback is that all new content in the docstring gets a pass, but only hyperlinks should be allowed to be "too long".

**Comment by ericmjl** [comment]
@hectormz let's use the trick that @bdice suggested.

In the future, 
I am going to push for us to use [semantic line breaks](https://sembr.org) 
rather than 79-character line breaks. 
We get more lines of docs, 
but they are easier to diff and read.
:smile:

**Comment by bdice** [comment]
@ericmjl I see what you did there. 😆 Glad to see that worked for you. Good luck!
