### ISSUE TITLE
[INF] Allow `import_message()` to be Python distribution flexible

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#559]
# Brief Description

Currently, if a user attempts to user a feature of an optional external package (`rdkit`, `biopython`, `unyt`, `pyspark`) which is not installed, the user receives an error that directs them on how to install it. The error message is displayed by `import_message()` which passes instructions on how to install it. Ex:
```
To use the janitor submodule spark, you need to install pyspark.
To do so, use the following command:
    conda install -c conda-forge pyspark
```
With the exception of `rdkit`, I think all of these packages are `pip` installable. It would be nice if this message could decide whether to provide `conda` vs `pip` instructions to the user. Or tell them that the package can only be installed with `conda`. 

This is how the function is currently called:
```python
import_message(submodule="spark", package="pyspark", 
    installation="conda install -c conda-forge pyspark")
```

Not all `conda` installs will use the same channel. One option is to provide both `conda` and `pip` instructions as arguments in the call, and it figures out which to send to the user. If either are `None`, then it is understood to be `pip` or `conda` only.

# Example API

One verbose option would be to extend what currently exists:
```python
import_message(submodule="spark", package="pyspark", 
    conda_installation="conda install -c conda-forge pyspark", 
    pip_installation="pip install pyspark")
```

A more succinct version could be:
```python
import_message(submodule="spark", package="pyspark", 
    conda_channel="conda-forge", pip_install=True)
```
which would use the provided `package` argument, and `conda_channel` could be `None` if it doesn't exist on `conda`.

**Comment by hectormz** [comment]
This answer on [StackOverflow](https://stackoverflow.com/questions/21282363/any-way-to-tell-if-users-python-environment-is-anaconda/21282816#21282816) should work to determine if the user has an Anaconda distribution.

**Comment by ericmjl** [comment]
This is great, @hectormz! Are you interested in taking this on? If not, please go ahead and tag it as available for hacking on!

**Comment by hectormz** [comment]
If anyone else is interested, they can claim it. Otherwise I can check back in claim it!

**Comment by hectormz** [comment]
I have this 😃, PR coming soon
