### ISSUE TITLE
[INF] Don't require column name arguments to be strings

### ISSUE THREAD

**Issue by rahosbach** [ericmjl/pyjanitor#564]
It occurs to me that there are methods within `pyjanitor` that require column name method arguments to be strings (specified in the docs and/or validated in the actual code).  Examples are `engineering.convert_units()` and the two methods in the finance submodule (both of which I've worked on...guilty as charged :))  

Pandas does not require column names to be strings, and this could pose a big limitation for one's workflow (depending on the data set).  I'm not sure how pervasive this issue is throughout the `pyjanitor` methods; but, it seems like a discussion worth having, potentially resulting in a sweep of the current code base to remove such limitations.

**Comment by szuckerman** [comment]
When you say that "column names don't need to be strings" for Pandas, do you mean that people need to directly use the object? i.e. instead of a passing a `"users"` string column people would pass `dat.users`?

I think the main difference between `pyjanitor` and `pandas` in this regard is that `pandas` is actually performing mutations on the passed-in `Series`. `pyjanitor` just needs to know the name of the columns to use for the manipulation.

A really easy hack would be to add a decorator function for each method that does the following:

```python
def get_column_name(col):
    if isinstance(col, str):
        return col
    else isinstance(col, pandas.core.series.Series):
        return col.name
```

**Comment by rahosbach** [comment]
@szuckerman Not quite.  What I'm saying is that users need to pass in column names to use (many of) the `pyjanitor` methods.  In some cases, this passed-in column name is required to be a string.  But, maybe the column name is actually an integer (for instance, a year).  In this case, if we try to require all passed-in column names to be strings, then a user wouldn't be able to work with such a `pandas` column.

Example: This is a completely valid `pandas dataframe` with integer column names:
``` python
import pandas as pd
df = pd.DataFrame({1999: [0, 1, 2], 2000: [1, 3, 5]})
df

   1999  2000
0     0     1
1     1     3
2     2     5
 
```

**Comment by szuckerman** [comment]
Ok, I get it now.

Maybe a `convert_column_names_to_strings` method instead? Or even a `fix_number_column_names` function (to append something like `year_` to the numbers). 

The problem with having integer column names is that you can't do `df.1999` it has to be `df[1999]`. `fix_number_column_names` could instead convert the column to be: `df.year_1999`.

By the way, I feel this issue happens all the time when pivoting data, and it does get annoying to not use the dot notation.

**Comment by rahosbach** [comment]
@szuckerman I agree whole-heartedly with your sentiment that not being able to use dot notation with non-string column names is annoying.  However, I feel like because non-string column names are supported by `pandas`, `pyjanitor` should support that capability (as much as possible).

Alternatively, your `fix_number_column_names` idea is promising if it's decided to move away from supporting non-string column names.

I suppose this is ultimately up to @ericmjl and you and the other collaborators to make an executive decision.

**Comment by ericmjl** [comment]
@rahosbach I think early on, I made a decision to force column names to be strings for convenience. If I'm not mistaken, `clean_names()` should automagically convert all column names to string type (I might be wrong, though, the codebase has grown!, and an assumption I made with the early API design is that `.clean_names()` would probably be the first function called on in the DataFrame.

I agree with you, though, that supporting non-integer column names is a good idea. No point imposing a new restriction if `pandas` supports it. I don't want to impose too much work on any one person to finish this for the whole codebase, though. Perhaps let's make a checklist of functions where this occurs? I'll then pin the issue, and maybe raise a boilerplate set of issues for each of them.

**Comment by rahosbach** [comment]
@ericmjl Sounds good.  Here is a preliminary list of submodule methods I see that either require string column names in the code itself or in the documentation for the method:

- `biology.join_fasta()` (docs only, code should work with non-strings I think)
- `chemistry.smiles2mol()` (docs only, code should work)
- `chemistry.morgan_fingerprint()` (docs only, code should work)
- `chemistry.molecular_descriptors()` (docs only, code should work)
- `chemistry.maccs_keys_fingerprint()` (docs only, code should work)
- `engineering.convert_units()` (docs and code need fixing)
- `finance.convert_currency()` (docs only, code should work)
- `finance.inflate_currency()` (docs and code need fixing)
- `ml.get_features_targets()` (docs only, code should work)

There are undoubtedly more in the `utils` and `functions` modules.  I just haven't the time to go through them yet.

**Comment by dendrondal** [comment]
So I wanted to take a crack at this, and noticed that ```clean_names()``` doesn't appear to do a string conversion automagically. The first function called is ```_change_case()```, which has a string type hint and calls .upper and .lower on the column names. 

I think it would be easy enough to do an inplace modification of the original column names in ```clean_names()```, but I was wondering if anyone is familiar with the valid types of a pandas column name? I've been looking through the pandas source and haven't found it explicitly described. I'm assuming it's just string/int/float, but wanted to be sure for annotation purposes in the functions described above.

**Comment by zjpoh** [comment]
I just want to point out that this might cause some problems to the `janitor.spark` module and reduce code reusability. However, currently there are only two functions in that module. So, fixing it should be rather easy.

**Comment by ericmjl** [comment]
> was wondering if anyone is familiar with the valid types of a pandas column name

cc: @tomaugspurger - would you be kind enough to help us here please? :smile:

**Comment by TomAugspurger** [comment]
I don't recall if it's written down anywhere, but generally we require that each column name be hashable. Unfortunately, it's not validated when the DataFrame is created, but most methods in pandas require it. Wish I had a better answer here :)

**Comment by dendrondal** [comment]
That gives me what I need! I can just replace ```str``` with ```typing.hashable``` in the functions mentioned. 

@zjpoh Thanks for the input, I'll be mindful of what these functions call when altering the functions module. I very much agree with your concern about reusability, since we need to make the concession of making the code more weakly typed in order to use dot notation. The only alternative I see would be to force sanitization of column names for any janitor method chain (i.e. having ```clean_names()``` called automatically rather than defined as the first df method by the user as @ericmjl  was discussing), and keeping the ```str``` typing. This would actually increase portability, as I believe [PySpark enforces string column names](https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=selectexpr#pyspark.sql.DataFrame.withColumnRenamed). This is obviously a very "opinionated" api decision, however. What do you all think?

**Comment by ericmjl** [comment]
While I'm personally in favour of `clean_names()` being called by default, I can also see a few cases where this isn't productive, some of which I've encountered in my own work too. An example is in chemistry, when column names have things like `[nM]` in there, and I take advantage of the string matching to automatically determine whether or not I should log10-transform the column in my code. (concentration values are generally ok to log-transform when doing ML)

Enforcing string names by default does sound sensible for labelled arrays, though. 

This is a very thoughtful discussion thus far, @dendrondal and @zjpoh. I don't want to be a barrier to action being taken though, so I'll leave a few points that will hopefully encourage action taken:

- As long as the behaviour is well-documented, and the pieces are built up in logical chunks that can be reverted (remember, we squash commits when merging), then I have no problem merging first while continuing the discussion.
- Be sure that no tests break :smile:

**Comment by zjpoh** [comment]
Yeap. I totally agree with @ericmjl. Pyspark module shouldn't be an impediment to adding / improving pyjanitor functionality.

**Comment by ericmjl** [comment]
@dendrondal has done a tremendous job with his PR, so I'm going to close this issue for now. We can reopen later if need be.
