### ISSUE TITLE
[ENH] Series toset() functionality

### ISSUE THREAD

**Issue by eyaltrabelsi** [ericmjl/pyjanitor#570]
# Brief Description

I would like to propose toset() functionality similar to [tolist()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.tolist.html). 
Basically it will be a function call to tolist and then conversion to set.
Note: if the collection has no hashable member it will raise an exception.

# Example API

Please modify the example API below to illustrate your proposed API, and then delete this sentence.

```python
# convert series to a set
df['col1'].toset()

**Comment by ericmjl** [comment]
@eyaltrabelsi great idea! In fact, I think you can pass in the `.values` array directly to the set constructor and return it.

Let me check - this would be a `pd.Series` method, is that right?

**Comment by eyaltrabelsi** [comment]
@eyaltrabelsi i prefer to use the tolist and then use set due to the fact that it holds casting mechanism as well, you can see [here](https://github.com/pandas-dev/pandas/blob/v0.25.1/pandas/core/base.py#L1160-L1181)

**Comment by ericmjl** [comment]
Awesomeness! Let me know if you'd like to take on this issue, and then I'll assign it. You've been busy contributing, don't want to keep the burden too high on you - we can build this slowly, which is how good software is made :smile:.

**Comment by eyaltrabelsi** [comment]
@ericmjl I would love to finish the previous one before :), if this wont be assigned i will take it afterwards

**Comment by eyaltrabelsi** [comment]
@ericmjl i would like to work on this :)
