### ISSUE TITLE
[ENH] Safe arithmetic transforms

### ISSUE THREAD

**Issue by jiafengkevinchen** [ericmjl/pyjanitor#582]
What kind of bugs me is that there is no pd.Series.log(), pd.Series.exp(), etc. function that chains the command. To make matters worse, if your Series has zeros, np.log on the Series would return -inf for the zero entries, which screws up any downstream computation --- raising a warning while returning np.nan would be a saner alternative. 

Proposal: add simple chain-able operations to pd.Series like
- .log(warn=True)
- .exp
- .logit(warn=True) [logit(x) = log(x/(1-x)]
- .sigmoid() [inverse logit]
- .probit(warn=True) [Phi^-1, where Phi is the standard normal CDF]
- .normal_cdf() [inverse of probit]
- .z_score() [standardize by centering and shrinking by standard deviation]

**Comment by zbarry** [comment]
@ericmjl - is there any reason we wouldn't want to add a `math.py` (or whatever) to put stuff like these things in?

**Comment by ericmjl** [comment]
@zbarry no reason to not build this, whatsoever!

@jiafengkevinchen would you like to get started on this?

**Comment by ericmjl** [comment]
@jiafengkevinchen I’m looking back on the PR associated with this issue, and I’m very impressed by the PR. Given the PR, I think we can close it, as all of the math functions specified have been implemented. Going to close; let’s raise another issue for new math functions as needed :smile:.
