### ISSUE TITLE
[ENH] Implement framework for adding xarray methods

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#586]
See PR #585 and general discussion #394 

I've currently implemented two methods, one that wraps a numpy array with the metadata from an xarray dataarray [`dataarray.clone_using(numpy_array)`] (kind of like the xarray equivalent of `np.zeros_like`), and one that converts an axis which contains datetime coordinates to human-readable floats of the desired unit (`convert_datetime_to_number`).

It uses the same methodology to register methods as the rest of pyjanitor:

```python
@register_dataarray_method
def new_method(da: xr.DataArray, some_params) -> xr.DataArray:
    do_stuff()
    return dataarray
```

It also includes a `register_dataset_method` decorator. These can be `@decorator1 @decorator2` chained to register the method for both `xr.Dataset`s and `xr.DataArray`s.

```python
da = xr.DataArray(np.random.randint(0, 100, size=(512, 1024)), dims=['random_ax_1', 'random_ax_2'], 
                  coords=dict(random_ax_1=np.linspace(0, 1, 512), random_ax_2=np.logspace(-2, 2, 1024)),
                  name='original')

da.clone_using(np.random.randn(512, 1024))

da.clone_using(np.random.randn(512, 1024), new_name='new_and_improved', use_coords=False)

(
    da.assign_coords(
        random_ax_1=1e9 * np.arange(512) * np.timedelta64(1, 'ns')
    )
    .convert_datetime_to_number('m', dim='random_ax_1')
)
```

**Comment by ericmjl** [comment]
Woohoo! Thanks @zbarry! I’m going to put a call on Twitter to see if others are interested in helping :smile:
