### ISSUE TITLE
[DOC] Fix type annotation issues in documentation 

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#589]
Two things that can be improved:

1) Type annotations in the docs hurt readability 

This is an example:

![image](https://user-images.githubusercontent.com/4762711/66703876-25f52700-ece5-11e9-8199-9f4d67767ad6.png)

I think we could alleviate this quite a bit by bolding the actual parameters names or something akin to that.

2) Abbreviated descriptions on the functions list page do weird things with type annotations and cut info out:

![image](https://user-images.githubusercontent.com/4762711/66703872-1d045580-ece5-11e9-99bd-096c8b497f25.png)

It might make sense to exclude type annotations here entirely.

**Comment by hectormz** [comment]
Is this purely in the realm of how docs get autogenerated, i.e. source code/docstrings don't need to be touched?

**Comment by ericmjl** [comment]
>Is this purely in the realm of how docs get autogenerated, i.e. source code/docstrings don't need to be touched? 

I think so. Wonder if there’s a sphinx config for this?

**Comment by ericmjl** [comment]
Oh wait, I think I found where this is controlled. 

https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
