### ISSUE TITLE
[INF] Add pre-commit hooks to repository

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#601]
Pre-commit hooks are a great way to push code style checks to the development machine, so that they automatically happen and thus we don't have to wait for the CI system to finish to  discover that it failed only on code style.

I will add in instructions to get started with `pre-commit`,  so that a bunch of checks are automatically done pre-commit.

**Comment by hectormz** [comment]
I *was just* thinking about proposing optional `pre-commit` hooks yesterday! awesome
