### ISSUE TITLE
[INF] Time to cut a new release

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#605]
Friends, it's time to release 0.18.3 now :smile:. We have accumulated enough changes that I think it warrants an update.

**Comment by ericmjl** [comment]
It's out in the wild! Anybody want to do a Twitter post? :smile: :tada:

**Comment by hectormz** [comment]
I don't have the same following as @ericmjl , but I can tweet about the new release! Which features do we want to highlight?

**Comment by hectormz** [comment]
Can we put in a quick commit to update the CHANGELOG from On Deck to 0.18.3?

**Comment by ericmjl** [comment]
Please go for it!
