### ISSUE TITLE
[ENH] add an expand_grid function

### ISSUE THREAD

**Issue by jcvall** [ericmjl/pyjanitor#617]
Recently watched a video by David Robinson on tidytuesday where he used the crossing function (a wrapper of the base r function expand_grid) from tidyr R library to do a Monte Carlo simulation.  I think this would a great addition to pyjanitor.  Don’t have the bandwidth at the moment to add it, but could in the near future.  I did come across a stackoverflow solution to this 

https://stackoverflow.com/questions/12130883/r-expand-grid-function-in-python

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jcvall-olympus** [comment]
With much trial and error I came up with this:
`
@pf.register_dataframe_method
def expand_grid(df: pd.DataFrame(), data_dict: dict, key: str):
    """Create a dataframe from every combination of given values."""  
    
    if key == 'None':
        rows = itertools.product(*data_dict.values())
        new_df = pd.DataFrame.from_records(rows, columns=data_dict.keys())
        return new_df
    
    else:
        data_dict.update({key:df[key]})
        rows = itertools.product(*data_dict.values())
        new_df = pd.DataFrame.from_records(rows, columns=data_dict.keys())
        final_df = df.merge(new_df, how = 'outer', on = key, sort= False)
        return final_df
`

**Comment by jcvall** [comment]
I will provide two examples later this afternoon. This requires intertools import. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jcvall-olympus** [comment]
First example:  creating a grid from a blank dataframe

![image](https://user-images.githubusercontent.com/48399986/72206781-e236c880-345f-11ea-810e-76dbb710d53e.png)

**Comment by jcvall-olympus** [comment]
Second example: creating with dataframe columns

![image](https://user-images.githubusercontent.com/48399986/72206856-84ef4700-3460-11ea-905b-5505221d2b11.png)

**Comment by jcvall-olympus** [comment]
Third example: with df column as index and additional custom columns

![image](https://user-images.githubusercontent.com/48399986/72206880-e9aaa180-3460-11ea-9d2e-851af4772806.png)

**Comment by jcvall-olympus** [comment]
I would like later add a jupyter notebook example of tidytuesday analysis using monte carlo simulation using the expand_grid function.

**Comment by samukweku** [comment]
checking here as well. are u still working on this @jcvall-olympus

**Comment by jcvall** [comment]
If you want to open this one up or take it on go ahead.  I would love to see it in pyjanitor.  This one I do want to contribute an example using a tidytuesday example on simulation.  If it doesn’t get attention in the next month or so I will try to take it on.  I have some weakness around testing in python. I need to get more up to speed.  A weakness of mine I need to work on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ericmjl** [comment]
@jcvall you've been doing great with your contributions to the library, and @samukweku I'm super happy that you've just jumped in and done stuff with us! 

@samukweku please do go ahead and take it on if you'd like to!

**Comment by samukweku** [comment]
made some progress on this and will send in a pull request. Not sure how to go about creating the pandas_flavor, since expand_grid should cover name value pairs, even if a dataframe is not involved. Or should I just focus solely on creating an expand_grid, similar to what R/tidyverse has, but just for dataframes?
