### ISSUE TITLE
[ENH] Proposing a "jitter" function

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#622]
# Brief Description

Had to use this at work recently, where I had to jitter the data that we had to slightly anonymize it.

All that we did here was to add Gaussian noise scaled by a fraction of the magnitude of each  value.

# Example API

This could operate at two levels: at the pandas Series and DataFrame levels. I implemented the "Series" version at work, but not the "DataFrame" one.

As a Series method, we would do something like this:

```python
from typing import Optional, Tuple

def jitter(s: pd.Series, scale_magnitude: np.number, clip: Optional[Tuple[float, float]] = None):
    """
    Jitter a pandas Series by applying Gaussian noise.
    
    By default, the jitter function takes the numeric value of each series element as the mean,
    and uses a multiplier of the numeric value (scale_magnitude) as the standard deviation.
    """
    loc = 0
    scale = s * scale_magnitude
    noise = np.random.normal(loc=0, scale=scale)
    result = s + noise
    if clip:
        result = np.clip(result, *clip)
        
    return result
```

I think it might be possible to do the analogous thing for DataFrames.

The API would look like the following:

```python
# series  API
s = df['column_name']
s.jitter()

# dataframe API
df = pd.DataFrame(...).jitter("column_name", scale_magnitude=0.1, clip=(0, None))
```

What do others think?

**Comment by anzelpwj** [comment]
I think it'd be great! Jitter is a very helpful tool for plotting.

I would suggest being able to set the random seed, if only for testing purposes.

**Comment by rahosbach** [comment]
It's been a while since I've contributed a PR :)  If no one else wants it, I'd be happy to put something together (hopefully in the next week or so).

This should be added to the functions module, I presume?

**Comment by ericmjl** [comment]
Woohoo, that’d be great, @rahosbach! 

Yes, functions sounds like the right place to put it. I can’t think of another place where this might fit.

**Comment by anzelpwj** [comment]
One other thought - if you have any data with 0 value, it won't get jittered, and if your data spans a order on magnitude or more, you'll see noticably differing levels of jitter. Maybe include the option for a constant about of jitter as well?

**Comment by rahosbach** [comment]
That's an interesting point, @anzelpwj.  

I've never had to implement a jitter function before, but one option might be to add an optional argument called `zero_scale` (or similar) where the user could input a floating point value that would correspond to `scale` parameter in `np.random.normal()' when the `s` value is 0.  That way, noise could still be randomly generated for those values.

Thoughts?  Bad idea?

**Comment by anzelpwj** [comment]
Maybe you have two parameters, `scale` and `scale_const`, and your jitter magnitude is `scale*x + scale_const`

**Comment by rahosbach** [comment]
But `scale` is used to set the standard deviation of the Gaussian distribution we're sampling the noise from (at least in @ericmjl's example).  So are you saying that the Gaussian standard deviation should be set to `scale*x + scale_const`?  In that case, `scale_const` acts in the same way as my proposed `zero_scale`.

To simplify things, what if we changed our approach to have the mean of the Gaussian distribution be the actual series value (`s`), and then the user simply specifies the `scale` parameter that will set the standard deviation of the Gaussian distribution?  Then, the actual values we sample are the jittered values, and we would avoid both the zero-magnitude issue and the issue of differing levels of jitter for series with a wide range of values.

Example:
```python
def jitter(s: pd.Series, scale_magnitude: np.number, clip: Optional[Tuple[float, float]] = None):
    result = np.random.normal(loc=s, scale=scale_magnitude)
    if clip:
        result = np.clip(result, *clip)
        
    return result

**Comment by ericmjl** [comment]
@anzelpwj @rahosbach I _think_ I'm correct on the following point, but would love to be corrected if I'm wrong: `constant + N(0, scale) == N(constant, scale)` - it's where the reparameterization trick in stats comes from, I think. 

Pragmatically, your implementation is probably less confusing than mine, @rahosbach, so let's go with your implementation. 

@anzelpwj if we have data that span multiple orders of magnitude, is it a better idea to jitter the log-transform? I don't know why but I have this hunch that this might be a "good" way to jitter, but if I'm wrong, let me know.

**Comment by anzelpwj** [comment]
Scaling the jitter by x value should basically jitter the log transform. But there's still the problem of pesky 0 values (or even negative values? Why shouldn't they get some of the fun?).

I see the code working like this

```
from typing import Optional, Tuple

def jitter(s: pd.Series, scale_magnitude: np.number, scale_constant: np.number = 0, clip: Optional[Tuple[float, float]] = None, random_state: np.number = None):
    """
    Jitter a pandas Series by applying Gaussian noise.
    
    By default, the jitter function takes the numeric value of each series element as the mean,
    and uses a multiplier of the numeric value (scale_magnitude) as the standard deviation.
    """
    if random_state is not None:
        np.random.seed(random_state)
    scale = s * scale_magnitude + scale_constant
    result = np.random.normal(loc=s, scale=scale)
    if clip:
        result = np.clip(result, *clip)
        
    return result
```

**Comment by rahosbach** [comment]
I guess I'm still wondering why `scale` needs to be tied to the actual series value, `s`?  In that case, you would see more jitter for larger values, and vice-versa, which doesn't sound necessary.

This is why I proposed letting the user set a constant `scale_magnitude` value that would be used, by itself, to define the standard deviation of the distribution we sample from.  In effect, this sets a constant jitter level that does not depend on the actual series value.  Then, if we set the distribution's mean to be the actual series value, then the value we sample will necessarily be a jittered value that we can use as the result.  _And_, this would even jitter 0 values.

Sorry to keep this thread going and going.  I just want to ensure I completely understand the implementation choices we're making and why we're making them.

**Comment by anzelpwj** [comment]
Mostly that's what I saw in Eric's original implementation `scale = s * scale_magnitude` -- if we want to just do a constant scale that could work as well, though maybe if we want to have constant jitter for a log-plot, then scaling based on series value would be a good idea.

**Comment by rahosbach** [comment]
Good point.  But, if the idea is to jitter for a log-plot, then couldn't the series values we use be log-transformed first?  Then, we would be adding jitter to (previously) log-transformed values and still adding a defined amount of random jitter.

Essentially, we would leave any log-transformation (as well as whatever `scale_magnitude` is appropriate) up to the user to handle prior to running this method.  I think that should still work.

**Comment by ericmjl** [comment]
@rahosbach in the spirit of explicit is better than implicit, I think you've nailed what the function ought to be like. Let's go ahead with what you have, what say you?

**Comment by rahosbach** [comment]
@ericmjl I'm happy to move ahead with the PR now.  @anzelpwj I'll be sure to add you as a reviewer on it so that you can see what I've done and provide any more suggestions.
