### ISSUE TITLE
Add add_count and add_total functions

### ISSUE THREAD

**Issue by jcvall-olympus** [ericmjl/pyjanitor#623]
I know there is functionality with groupby_agg here, so I have been going back and forth on this one.  But like the tidyverse there are helper functions the are more direct like tally or add_count, where you could use summarize() and count() or n() together to get the same output.  

I am not deeply invested in this suggestion, so if you think that groupby_agg can work here alone, I am fine with that.  

Here are the two proposed functions I could possibly add:

add_count function
```
@pf.register_dataframe_method
def add_count(df: pd.DataFrame(), count_column: str, new_column_name: str, include_na: bool):
    """Add countby column on target column"""  
    
    if include_na == True:
        df[new_column_name] = df.groupby([count_column])[count_column].transform('count')
        num = df[new_column_name].isna().sum()
        df[new_column_name].fillna(num, inplace= True)
        return df
    
    else:
        df[new_column_name] = df.groupby([count_column])[count_column].transform('count')
        return df

```

add_total function
```
@pf.register_dataframe_method
def add_total(df: pd.DataFrame(), sum_columns: list, new_column_name: str, axis: int, skipna: bool):
    """Add countby column on target column"""  
    
    if axis == 1:
        df[new_column_name] = df[sum_columns].sum(axis= axis, skipna = skipna )
        return df

    else:
        df[new_column_name] = df[sum_columns].sum(axis= axis, skipna = skipna ).sum()
        return df
```

**Comment by ericmjl** [comment]
@jcvall-olympus this is a great suggestion! Aliases that make things easier are always good. :smile:. 

Would you like to work on this? If so, I’ll assign this one to you! In terms of what to put inside the PR, I’d suggest doing one function at a time, e.g. let’s add in a `tally` or `add_count` function first.

**Comment by jcvall** [comment]
I plan on upload my functions.  I hope to do them in a few weeks.  Sorry for the delay.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samukweku** [comment]
stil working on this? if u are not, I would love to give it a go

**Comment by jcvall** [comment]
Go ahead Sam.  Thanks for taking this one on. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samukweku** [comment]
Pandas 1.1.0 has some updates that I think will be useful for ``` groupby_agg ```  and by extension ```count``` - a parameter for including or excluding null values in groupby has been added. Just waiting for the release and I will push off on some functions for this issue
