### ISSUE TITLE
[ENH] Complete `functions.reset_index_inplace()` deprecation

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#639]
# Brief Description

`functions.reset_index_inplace()` was marked for deprecation in `0.18` release. It was marked in #282 on May 7, 2019. Should it be removed now?

**Comment by ericmjl** [comment]
Yes, I think it's a good time to remove it. Thanks for the catch, @hectormz! To keep things streamlined for you, I don't mind if you sneak in this fix into #641.

**Comment by hectormz** [comment]
Sure, I'll do that

**Comment by hectormz** [comment]
This is closed via #641
