### ISSUE TITLE
Unused `df` in `test_inflate_currency.py` tests

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#642]
# Brief Description

The `df`s created in `test_expected_result()` and `test_expected_result_with_full_country_name()` in `test_inflate_currency.py` are created but not used in the tests.

Is this the intended use, or do they need to be corrected? I believe they were both added in #485 . Perhaps @rahosbach would be able to take a look at them. 

Thanks!

**Comment by hectormz** [comment]
I think I have addressed in #641. Will push new commits soon and can close this when passed

**Comment by rahosbach** [comment]
Thanks for catching that, Hector.  You are correct; I think the final call where column `a` is summed needs to refer to `df`, not `dataframe`.  However, I looked at #641 and didn't see any such changes to these methods in your commits.  Are you sure you made those corrections (or similar)???

**Comment by hectormz** [comment]
Hi @rahosbach I recently made that change, but haven't pushed it yet. Will do so in a few minutes! I guess the test passed anyway because `dataframe` updated in place?

**Comment by rahosbach** [comment]
Perfect @hectormz .  And yes, that's what's happening—the method mutates the original dataframe.  So, it may make sense in the test to just re-assign `df` to `dataframe`, which is more aligned with the method's intention.

**Comment by hectormz** [comment]
This is closed via #641
