### ISSUE TITLE
[BUG] transform column mutates dataframe

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#645]
I think it does so, and it shouldn't. Just leaving this here for my future reference.

The simple fix would be to add a `df.copy()` right before doing anything to the dataframe.

**Comment by VPerrollaz** [comment]
Hello,
looking at the code of the function `transform_column`, both [apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html) and [assign](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html) create new objects.
However the following code

```python
from io import StringIO
import pandas as pd
import janitor

donnees = """First name, Last name, Year of birth, Year of death
Isaac, Newton, 1642, 1726
Albert, Einstein, 1879, 1955
James, Maxwell, 1831, 1879
Henri, Poincaré, 1854, 1912"""
df = pd.read_csv(StringIO(donnees)).clean_names()

print(df)
df.transform_column("_year_of_birth", lambda x: x - 18)
print(df)
janitor.functions.transform_column(df, "_year_of_birth", lambda x: x + 18)
print(df)

dest_column_name = None
elementwise = True
if dest_column_name is None:
    dest_column_name = column_name

if elementwise:
    result = df[column_name].apply(function)
else:
    result = function(df[column_name])

df.assign(**{dest_column_name: result})
print(df)

```
does produce the following printing

```
  first_name _last_name  _year_of_birth  _year_of_death
0      Isaac     Newton            1642            1726
1     Albert   Einstein            1879            1955
2      James    Maxwell            1831            1879
3      Henri   Poincaré            1854            1912
  first_name _last_name  _year_of_birth  _year_of_death
0      Isaac     Newton            1624            1726
1     Albert   Einstein            1861            1955
2      James    Maxwell            1813            1879
3      Henri   Poincaré            1836            1912
  first_name _last_name  _year_of_birth  _year_of_death
0      Isaac     Newton            1606            1726
1     Albert   Einstein            1843            1955
2      James    Maxwell            1795            1879
3      Henri   Poincaré            1818            1912
  first_name _last_name  _year_of_birth  _year_of_death
0      Isaac     Newton            1606            1726
1     Albert   Einstein            1843            1955
2      James    Maxwell            1795            1879
3      Henri   Poincaré            1818            1912 
```

So at this point I wonder if this is not the decorator that is causing the bug?

**Comment by ericmjl** [comment]
@VPerrollaz thanks for pinging in! I just did a test using the code you've provided, and got the following: https://gist.github.com/ericmjl/83ffa4fe21d0c9220da6159b39d629f3.

My hunch here is that you might be using an old installation of pyjanitor. As far as I can see, with the latest version of pyjanitor, no in-place modification of columns happens.

**Comment by VPerrollaz** [comment]
After a new clean install of the repostory and a conda environment I completely agree.

**Comment by ericmjl** [comment]
With the latest patch release, I think this issue can be closed. But please feel free to ping again if this issue persists.

**Comment by VPerrollaz** [comment]
Should be put a test somewhere for some garantee?

**Comment by ericmjl** [comment]
That's a great idea! Do you have a bit of bandwidth to handle this? If so, let me know. In the mean time, I'm going to create a new issue for this matter.
