### ISSUE TITLE
Test that transform_column does not mutate original

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#657]
Linked from issue #645.

> Should be put a test somewhere for some garantee?
> 
> _Originally posted by @VPerrollaz in https://github.com/ericmjl/pyjanitor/issues/645#issuecomment-630170156_

Possible test outline (just pseudo code, don't treat it as real code):

```python
def test_transform_column_does_not_mutate_original():
    df_transformed = df.transform_column("some_col", some_func)
    with pytest.raises(AssertionError):
        pd.testing.assert_frame_equal(df, df_transformed)
```

**Comment by ericmjl** [comment]
@VPerrollaz I put a test sketch up there - it might need a bit of working. (And it needs a docstring!) Let me know if you'd like to take it on.

**Comment by VPerrollaz** [comment]
I will give it a go, though I will need a bit of time to get familiar with the style of the code.

**Comment by ericmjl** [comment]
No pressure, I'm always happy to see new contributors come on board!
