### ISSUE TITLE
`df` annotation lacking in `find_replace` function of `functions.py` submodule

### ISSUE THREAD

**Issue by VPerrollaz** [ericmjl/pyjanitor#661]
# Brief Description

`df` annotation lacking in `find_replace` function of `functions.py` submodule.
It seems to be the only function for which there is no type annotation for the dataframe. Clearly not critical.

**Comment by ericmjl** [comment]
@VPerrollaz @VPerrollaz thank you for raising! If you're open to do the PR, I'd be happy to accept it. :smile: Let me know if you need help of any kind getting started.

**Comment by hectormz** [comment]
@VPerrollaz if you want to make a day of it, maybe there are some other missing annotations you could throw into the PR 😁. @ericmjl do I recall you mentioned you were looking into trying out `mypy` with `pyjanitor`? Could that help us check coverage? I've never actually used it myself.
