### ISSUE TITLE
[ENH] support .query()-style strings in df.update_where()

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#663]
Given the `update_where` example:

```python
# The dataframe must be assigned to a variable first.
data = {
    "a": [1, 2, 3, 4],
    "b": [5, 6, 7, 8],
    "c": [0, 0, 0, 0]
}
df = pd.DataFrame(data)
df = (
    df
    .update_where(
        condition=(df['a'] > 2) & (df['b'] < 8),
        target_column_name='c',
        target_val=10)
    )
```

It would be nice to be able to use `.query`'s style instead to avoid having to use `df.pipe()` if `df` has been modified somewhere along your method chain block:

```python
df = (
    pd.DataFrame(data)
    .update_where(
        condition='a > 2 and b < 8',
        target_column_name='c',
        target_val=10)
    )
)
```

**Comment by samukweku** [comment]
I would love to work on this

**Comment by samukweku** [comment]
Hi @zbarry , if it's ok with you, I would love to work on this.

**Comment by zbarry** [comment]
That’d be great. Thanks!

**Comment by samukweku** [comment]
@zbarry Cool. I'll start off on it. Is it required that you assign it to me?

**Comment by zbarry** [comment]
Good point; I went ahead and assigned it.
