### ISSUE TITLE
Rename dataframe inplace

### ISSUE THREAD

**Issue by shantanuo** [ericmjl/pyjanitor#67]
Is this possible with janitor?
df.clean_names(inplace=True)

**Comment by shantanuo** [comment]
"inplace" parameter is not really needed. But I suggested it because a lot of pandas methods use it and clean_function will look like a native pandas method with this. 
Which one of these 2 statements look more pythonic?
df=df.clean_names()
df.clean_names(inplace=True)
I guess the user should have both the options available.

**Comment by ericmjl** [comment]
@shantanuo the expected use case of `.clean_names()` is usually after the data frame is constructed. Hence the examples:

```python
df = (
    pd.read_csv(...)
    .clean_names()
    # chain more functions down here
)
```

**Comment by shantanuo** [comment]
I have never used this style, nor have I seen others chaining immediately after read_*  
I am not an expert, I will like to know what does the community think about it.

**Comment by ericmjl** [comment]
No worries, good to know. Btw, if you're interested in reading more of why I decided to put `pyjanitor` together, and develop it with the rest of the community, here's a document I'm working on: https://github.com/ericmjl/pyjanitor/blob/whitepaper/paper/manuscript.md
