### ISSUE TITLE
[TST] Use pandas.testing for compatibility

### ISSUE THREAD

**Issue by hectormz** [ericmjl/pyjanitor#674]
# Brief Description

`test_expand_grid.py` imports from `pandas._testing`, which is a more recent module in `pandas`, and doesn't exist in previous versions of `pandas`. Instead, other tests have imported from `pandas.testing` which still exists in newer versions of `pandas`. This is only an issue if we're keeping `pyjanitor`'s `pandas` compatibility at > 0.24, which means that we should also test/develop with that version as well.

https://github.com/ericmjl/pyjanitor/blob/62ee72fc5ed2fe6d80acc6663d222458252c03de/tests/functions/test_expand_grid.py#L6

This fix is a simple one, and could be combined with #675

**Comment by ericmjl** [comment]
@hectormz thanks for the catch! All tests pass with `pandas = 1.x` nowadays, is that right? If so, I think we can safely pandas to 1.0 minimum.

**Comment by hectormz** [comment]
Yup, all tests pass, I assume `pandas.testing` will eventually be removed in favor of `pandas._testing`. So we could go ahead and make `pandas>=1.0.0` the minimum. How are package requirements handled for `conda`? I see `environment-dev.yml`, but I assume that is for those developing, but not sure how it works for those installing from `conda-forge`

**Comment by hectormz** [comment]
Actually, looking closer at this, I think if possible, we should use the public testing module from `pandas` instead. But looking through our usage of `pandas.testing`, I see that most of the time we do this:
```python
import pandas as pd
...
pd.testing.assert_frame_equal(...)
```
and a few times we have this pattern:
```python
from pandas.testing import assert_frame_equal
...
assert_frame_equal(...)
```

Do you strongly favor one pattern over the other?

We only seem to use `assert_frame_equal` and `assert_series_equal` from `pandas.testing`

I think we should still move forward with requiring `pandas>=1.0.0`

For clarity sake, requiring `>=1.0.0` and making this usage more uniform should be separate PRs.

**Comment by hectormz** [comment]
After some thought, I think I like

```python
from pandas.testing import assert_frame_equal
...
assert_frame_equal(...)
```

I think `assert_frame_equal`/`assert_series_equal` are clear enough, and save some repeated characters.

Let me know if you have any conflicting thoughts, or stop me in the PR 😉

**Comment by ericmjl** [comment]
@hectormz Go ahead with it! Also see if you might be able to find a good place on the docs for this pointer. 😸
