### ISSUE TITLE
Some functions not showing on the API documentation page

### ISSUE THREAD

**Issue by samukweku** [ericmjl/pyjanitor#678]
Noticed that some functions are missing from the API documentation page. ```unionize_dataframe_categories``` and ```move``` functions are not listed on the API docs page. Not sure which other ones are missing. Not sure how this can be fixed; if anyone can point me on how to fix it (if I can), that would be great.

**Comment by ericmjl** [comment]
@samukweku thanks for the catch!

I think what needs to happen is that the functions get added to [docs/reference/general_functions.rst](https://github.com/ericmjl/pyjanitor/blob/dev/docs/reference/general_functions.rst), under the appropriate category. From there, they will get listed as a table, and a link will show up to get them added to the docs page!

**Comment by samukweku** [comment]
@ericmjl , cool. Is this an automated process ?

**Comment by ericmjl** [comment]
@samukweku yep, indeed! Once you add it to that page, Sphinx, which builds the docs, will automatically parse that page, find the relevant functions in the codebase, generate the child docs pages, and link them up. It's superb!

**Comment by samukweku** [comment]
Alright, kindly assign this to me.

**Comment by ericmjl** [comment]
Done @samukweku! :smile: Thanks for taking this on! (And be sure to stay safe and sane down under!)

**Comment by samukweku** [comment]
Sure will. Just as a side note, I have signed up for ```codecov``` and ```travis```; I could not get ```pyjanitor``` on``` codecov``` ( or I probably am not doing something right). I'll read up more on these tools and wait for you to put us (I and @zbarry ) on the tools with respect to ```pyjanitor```. Cheers, and stay safe as well!
