### ISSUE TITLE
Warning shows up with adding new attributes

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#68]
@shantanuo this appears to be related to your earlier PR. When I run tests, this shows up consistently.

```
  /Users/maer3/github/software/pyjanitor/janitor/functions.py:143: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
    df.original_columns = original_column_names
```

From your reading, do you know of an appropriate way to attach a new dataframe attribute without invoking this warning?

**Comment by zbarry** [comment]
The @ didn't go through

**Comment by ericmjl** [comment]
Resolved, thanks @shantanuo!
