### ISSUE TITLE
Diffing two dataframes

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#697]
# Brief Description

From a chat in the SciPy 2020 virtual slack, I would like to propose adding a `df1.diff_against(df2)` function.

Diffing stuff can get pretty complex, so I'd advocate to start simple and not rush to an implementation. In particular, defining the key categories of diffing, and how they would work, is probably the important piece here.

In diffing two dataframes, the function should probably report the following minimum categories of differences:

1. Differences in column names.
1. For overlapping column names, differences in dtypes
1. For overlapping column names, differences in values
1. Difference in row indices (i.e. which row indices are present in one but not the other)
1. For overlapping row indices, differences in values (dtypes irrelevant here)
1. Differences in nullity.

# Example API

I think the key behaviour here is that each category of diff should be controlled by its own kwarg. 

I don't know which design is better:

```python
# The skeleton, which does not have any kwargs set, and should return a full diff.
df.diff_against(df2)

# Compare column names only:
df.diff_against(df2, diff_column_names=True)

# Compare overlapping column names' dtypes and values only:
df.diff_against(df2, diff_column_data=True)
```

OR:

```python
# The skeleton, which does not have any kwargs set, and should **error out**.
df.diff_against(df2)

# Compare column names only:
df.diff_against(df2, diff_column_names=True)

# Compare overlapping column names' dtypes and values only:
df.diff_against(df2, diff_column_data=True)

# Diff everything
df.diff_against(df2, diff_all=True)
```

OR something else?

Also, what should the output look like?

- Python warnings/logging?
- Raise an error, so this can be used in tests?

I will raise this on the SciPy slack to solicit community suggestions.

**Comment by milicag** [comment]
Thanks @ericmjl for putting this together! Also average absolute and relative errors per some given slice defined using say groupby, as well as min and max absolute and relative error (in each grouping if desired). The stuff that https://pandera.readthedocs.io/en/latest/index.html does is also useful.

**Comment by VPerrollaz** [comment]
I wonder if having some real world scenarios wouldn't help to define the API and the result.

**Comment by ericmjl** [comment]
@VPerrollaz yes, it would. Haha, I also realized why I usually have to do a double-take when reading your replies, it's because of the writing style!

But in any case, because the topic came out of SciPy 2020, and in the chat someone also found the tool [daff], I'm going to close this issue. It was a nice intellectual activity though.

[daff]: https://github.com/paulfitz/daff

**Comment by VPerrollaz** [comment]
Since english is not my mother tongue don't hesitate to point out if I say something weird. 
Daff seems indeed pretty powerful and in particular does patches which seemed hard to implement.

**Comment by ericmjl** [comment]
> Since english is not my mother tongue don't hesitate to point out if I say something weird.

Your English is actually impeccable! I guess I read a direct style more easily. For example, the sentence 

> I wonder if having some real world scenarios wouldn't help to define the API and the result.

I might have written it as:

> I wonder if having some real world scenarios could help to define the API and the result.

The implied message is the same, which is an irony of the English language -- go make some examples! (haha!)

I'd say your use of the former form tells me your mastery over English is pretty awesome :). (In some corners of the English-speaking world, it'd be called "pretty _badass_", which is yet another ironic wart in the language!)

Anyways, this wasn't a critique of your language skills, it's really good :smile:. I just finally came to the realization that my head has been so attuned to direct style of communication. haha. :)

**Comment by VPerrollaz** [comment]
Thank you, I'm never completely sure of how clear I am in english. To be honest I think even in french I tend to use way too many indirection.
