### ISSUE TITLE
[ENH]: Groupby Top K

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#710]
# Brief Description

I would like to propose a function that allows users to take in a dataframe and return another dataframe that has the top "k" values after grouping by another column.

This has come up multiple times at work, when I have to pick out "top protein mutants in each cluster".

Posting this here in case anybody wants to take a formal stab at it, otherwise I'll get to it later.

# Example API

```python
def groupby_topk(d: pd.DataFrame, groupby_column_name: Hashable, sort_column_name: Hashable, k: int, sort_values_kwargs: Dict) -> pd.DataFrame:
    """
    Return a dataframe that has the top "k" values per group.
    
    Some docstrings to flesh out:
    - Groups: defined by the "groupby" column.
    
    Taken inspiration from https://stackoverflow.com/a/27844045/1274908
    """
    return d.groupby(groupby_column_name).apply(lambda df: df.sort_values(sort_column_name, **sort_values_kwargs).head(k))
```

Give it a thumbs up if you're interested in seeing this too!

**Comment by mphirke** [comment]
Hi, the example API you mentioned would return grouped output, but it will only reveal so for the class that is on the top after sort_values.

The output is like this if groupby column is species and sort column is petal length. 

sepal_length | sepal_width | petal_length | petal_width | species
-- | -- | -- | -- | --
4.6 | 3.6 | 1.0 | 0.2 | setosa
4.3 | 3.0 | 1.1 | 0.1 | setosa
5.8 | 4.0 | 1.2 | 0.2 | setosa
5.0 | 3.2 | 1.2 | 0.2 | setosa
5.5 | 3.5 | 1.3 | 0.2 | setosa

However, `top protein mutants in each cluster` makes me believe that it is required to return the top few for each species, which can be achieved by 

```
def groupby_topk_2(d: pd.DataFrame, groupby_column_name: Hashable, sort_column_name: Hashable, k: int, sort_values_kwargs: Dict) -> pd.DataFrame:
    """
    Return a dataframe that has the top "k" values per group.
    
    Some docstrings to flesh out:
    - Groups: defined by the "groupby" column.
    
    Taken inspiration from https://stackoverflow.com/a/27844045/1274908
    """
    return d.sort_values([groupby_column_name,sort_column_name],**sort_values_kwargs).groupby(groupby_column_name).head(k)
```
whose output for the same would be 

sepal_length | sepal_width | petal_length | petal_width | species
-- | -- | -- | -- | --
4.6 | 3.6 | 1.0 | 0.2 | setosa
4.3 | 3.0 | 1.1 | 0.1 | setosa
5.8 | 4.0 | 1.2 | 0.2 | setosa
5.0 | 3.2 | 1.2 | 0.2 | setosa
4.7 | 3.2 | 1.3 | 0.2 | setosa
5.1 | 2.5 | 3.0 | 1.1 | versicolor
4.9 | 2.4 | 3.3 | 1.0 | versicolor
5.0 | 2.3 | 3.3 | 1.0 | versicolor
5.0 | 2.0 | 3.5 | 1.0 | versicolor
5.7 | 2.6 | 3.5 | 1.0 | versicolor
4.9 | 2.5 | 4.5 | 1.7 | virginica
6.2 | 2.8 | 4.8 | 1.8 | virginica
6.0 | 3.0 | 4.8 | 1.8 | virginica
5.6 | 2.8 | 4.9 | 2.0 | virginica
6.3 | 2.7 | 4.9 | 1.8 | virginica

`

Which of the two outputs is to be achieved?

Notebook that I used for reference and testing: https://colab.research.google.com/drive/1o9_MMXM6JEhfZI4a2c_ZSRyBvMyA_3Qn#scrollTo=fI-96IWoCYol&uniqifier=1

**Comment by mphirke** [comment]
Sorry, notebook link I shared earlier was not correct.

Here is the correct link: https://colab.research.google.com/drive/1o9_MMXM6JEhfZI4a2c_ZSRyBvMyA_3Qn?usp=sharing

**Comment by ericmjl** [comment]
@mphirke that’s a great catch! In my original post, I actually put the `.head(k)` piece in the wrong place. I’ve edited the code block so it reflects the correct thing.

**Comment by mphirke** [comment]
I have not contributed to this repo before, but yes, I would like to work on it.

**Comment by ericmjl** [comment]
Awesomeness! We have docs on how to get started contributing. Definitely head over to the [contributing page](https://pyjanitor.readthedocs.io/contributing.html) to see how to get setup and started. If you’re familiar with the `git` way of working (i.e. GitFlow), then you’ll definitely feel at home here!
