### ISSUE TITLE
Add the ability to test whether data is changing/jumping beyond a tolerance 

### ISSUE THREAD

**Issue by UGuntupalli** [ericmjl/pyjanitor#711]
# Brief Description

Following up on #703, this issue seeks to introduce the ability to test whether in each column in a data frame the change between every two rows is within a user-defined range of values.

I would like to propose..
# Example API
```python
import pandas as pd
import numpy as np

# Create a random data frame
df = pd.DataFrame(data=[["2015-01-01 00:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 01:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 02:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 03:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-01 04:00:00", -0.65, 2, 2, 1.0],
                        ["2015-01-01 05:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 06:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 07:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 08:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-01 09:00:00", -0.65, 2, 2, 1.0],
                        ["2015-01-01 10:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 11:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 12:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 13:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-01 14:00:00", -0.65, 2, 2, 1.0],
                        ["2015-01-01 15:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 16:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 17:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 18:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-01 19:00:00", -0.65, 2, 2, 1.0],
                        ["2015-01-01 20:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 21:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 22:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 23:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-02 00:00:00", -0.65, 2, 2, 1.0]],
                  columns=['DateTime', 'column1', 'column2', 'column3', 'column4'])

# Set the index
df["DateTime"] = pd.to_datetime(df["DateTime"])
df.set_index("DateTime", inplace=True)

# Flag functionality 
df1 = df.copy(deep=True)

def flag_jumps(
        df_input: pd.DataFrame,
        tolerance: float = 10**-2
) -> pd.DataFrame:
    """
    Returns a data frame the size of the input

    Flags rows in each column where tolerance is violated
    :param df_input: input data frame to test for jumps
    :param tolerance: acceptable value of tolerance
    :return: data frame with flags indicating whether tolerance has been violated or not
    """
    # Calculate the difference between every two rows
    df2 = df_input.diff()

    # Check for tolerance violation
    df3 = df2.gt(tolerance)

    return df3

jump_flags = flag_jumps(df1, tolerance=2)
print(jump_flags)
```

**Comment by loganthomas** [comment]
I'd like to claim this issue. Planning my Hacktoberfest early 🎃

**Comment by ericmjl** [comment]
Assigned!

**Comment by loganthomas** [comment]
@ericmjl 

I've mulled this over in my head today and have a few open-ended points to bring up as well as a few clarifying questions

## Open-Ended Points (need some guidance here)

1. I originally thought that using "percent change" rather than "difference" for thresholding would be a better implementation.
    - Using a percent change paradigm for flagging allows users to define a universal unit that applies in context to each column. Take the below example:

    ```python
    In [1]: import pandas as pd

    In [2]: df = pd.DataFrame(
       ...:     {'a': [0.75, 2.25, 2.5], 'b': [2, 5, 8], 'c': [300, 303, 306]}
       ...: )

    In [3]: df
    Out[3]:
          a  b    c
    0  0.75  2  300
    1  2.25  5  303
    2  2.50  8  306

    In [4]: df.diff()
    Out[4]:
          a    b    c
    0   NaN  NaN  NaN
    1  1.50  3.0  3.0
    2  0.25  3.0  3.0

    In [5]: df.diff().gt(2)
    Out[5]:
           a      b      c
    0  False  False  False
    1  False   True   True
    2  False   True   True
    ```
    - In the above example, an arbitrary threshold (`2`) is used that applies to all columns in the dataframe. This may be appropriate for the first and second columns (`'a'` and `'b'`) but may not be applicable to the third column `'c'`. A difference threshold of `2` in the context of numbers that range from `[0.75, 2.5]` or `[2, 8]` may capture a large change, while a threshold of `2` in the context of numbers that range from `[300, 306]` may not hold a lot of weight.
    - By using a percent change threshold, we may be able to capture large variations **in the context** of each column:

    ```python
    In [6]: df
    Out[6]:
          a  b    c
    0  0.75  2  300
    1  2.25  5  303
    2  2.50  8  306

    In [7]: df.pct_change()
    Out[7]:
              a    b         c
    0       NaN  NaN       NaN
    1  2.000000  1.5  0.010000
    2  0.111111  0.6  0.009901

    In [8]: df.pct_change().gt(1)
    Out[8]:
           a      b      c
    0  False  False  False
    1   True   True  False
    2  False  False  False
    ```
    - By using a percent change threshold, we can see that column `'a'` doubled in size from row `0` to row `1` and that column `'b'` increases by a unit of `1.5`. We also see that column `'c'` isn't changing very much in the context of its original values.
    - I am thinking that setting a threshold of `2` and applying it with a difference method may *incorrectly* flag column `'c'` as changing or jumping beyond a tolerance (i.e. column `'c'` changing `0.1%` or `0.99%` is much smaller than changing `200%` or `150%` in the cases of columns `'a'` and `'b'`).

    - **Where this breaksdown** is when negative values are introduced:

    ```python
    In [1]: df = pd.DataFrame(
        ...:     {'a': [1, 2, 4], 'b': [-1, -2, -4], 'c': [-1, 2, 0]}
        ...: )

    In [2]: df
    Out[2]:
       a  b  c
    0  1 -1 -1
    1  2 -2  2
    2  4 -4  0

    In [3]: df.pct_change()
    Out[3]:
         a    b    c
    0  NaN  NaN  NaN
    1  1.0  1.0 -3.0
    2  1.0  1.0 -1.0
   ```
    - In the above, notice that column `'b'` and column `'c'` percentage change are a bit counter-intuitive.
    - Column `'b'` is *decreasing* from `-1` to `-2` to `-4`, but has a percentage change of `1.0` and `1.0`.
    - Similarly, `'c'` is *increasing* from `-1` to `2` and then *decreasing* from `2` to `0`. However, the percentage of change is `-3.0` and `-1.0` respectively.
    - This doesn't present an issue if we treat the percentage change as an absolute value (i.e. flag where the values are *either* increasing or decreasing beyond a certain percentage), but it leads me to where I was *eventually going to go* before encountering this hurdle (# 2 below is where I was heading).


2. Do we want to allow for multiple "condition methods" when applying this function:
    - Suppose one user wants to see the flags when anything in a dataframe is beyond a certain threshold **in either direction**.
    - Suppose another user wants to see flags when anything in a dataframe is **strictly above** a certain threshold.
    - Suppose another user wants to see flags when anything in a dataframe is **strictly below** a certain threshold.
    - I think the above scenarios pertain to (1) seeing any type of variation (in the positive *or* negative direction) (2) seeing only *increasing* variations (strictly positive and over a threshold) (3) seeing only *decreasing* variations (strictly negative and over a threshold)
    - This presents an interesting problem if we go with the percentage change route. Consider this example:

    ```python
    In [1]: df = pd.DataFrame(
        ...:     {'a': [1, 2, 4], 'b': [-1, -2, -4], 'c': [-1, 2, 0]}
        ...: )

    In [2]: df
    Out[2]:
       a  b  c
    0  1 -1 -1
    1  2 -2  2
    2  4 -4  0

    In [3]: df.pct_change()
    Out[3]:
         a    b    c
    0  NaN  NaN  NaN
    1  1.0  1.0 -3.0
    2  1.0  1.0 -1.0
   ```

    - If we wanted to flag all values where a percentage of change is greater than `50%` *in either direction*, we can use `.abs()`:

    ```python
    In [38]: df.pct_change().abs().gt(0.5)
    Out[38]:
           a      b      c
    0  False  False  False
    1   True   True   True
    2   True   True   True
    ```
    - If we wanted to flag all values that were **strictly increasing**, we wouldn't be able to accuratley represent this with a `.gt()`:

    ```python
    In [1]: df = pd.DataFrame(
        ...:     {'a': [1, 2, 4], 'b': [-1, -2, -4], 'c': [-1, 2, 0]}
        ...: )

    In [2]: df
    Out[2]:
       a  b  c
    0  1 -1 -1
    1  2 -2  2
    2  4 -4  0

    In [3]: df.pct_change().gt(0.5)
    Out[3]:
           a      b      c
    0  False  False  False
    1   True   True  False
    2   True   True  False
    ```
    - The above shows that column `'b'` would be flagged as increasing when in reality it is increasing in the negative direction (i.e. truly decreasing).

    - This leads me to think, hmmm maybe an arbitrary threshold would work then... In the scenario above, a `.diff()` method would yield the difference in the true positive and negative direction:

    ```python
    In [1]: df
    Out[1]:
       a  b  c
    0  1 -1 -1
    1  2 -2  2
    2  4 -4  0

    In [2]: df.diff()
    Out[2]:
         a    b    c
    0  NaN  NaN  NaN
    1  1.0 -1.0  3.0
    2  2.0 -2.0 -2.0
    ```
    - Here, we can capture increases and decreases and flag accordingly:

    ```python
    In [3]: df
    Out[3]:
       a  b  c
    0  1 -1 -1
    1  2 -2  2
    2  4 -4  0

    In [4]: df.diff()
    Out[4]:
         a    b    c
    0  NaN  NaN  NaN
    1  1.0 -1.0  3.0
    2  2.0 -2.0 -2.0

    In [5]: # Either increasing or decreasing beyond a threshold
        ...: df.diff().abs().gt(1.5)
    Out[5]:
           a      b      c
    0  False  False  False
    1  False  False   True
    2   True   True   True

    In [6]: # Strictly increasing beyond a threshold
        ...: df.diff().gt(1.5)
    Out[6]:
           a      b      c
    0  False  False  False
    1  False  False   True
    2   True  False  False

    In [7]: # Strictly decreasing beyond a threshold
        ...: df.diff().lt(0) & df.diff().abs().gt(1.5)
    Out[7]:
           a      b      c
    0  False  False  False
    1  False  False  False
    2  False   True   True
    ```
    - If we do stay with the arbitrary threshold approach (not the percentage change), I'd suggest a way to allow the user to declare a *universal* threshold as well as a way to declare a threshold per column. This kind of solves the idea of having a dataframe that spans multiple decades across columns (the `2` vs `[300,306]` discussion above).
    - At this point, I'm at a loss. I like the idea of the percentage change, but can see how trying to flag for specific scenarios would present issues. I like the ease of filtering with the `.diff()` approach, but think we need a way for uses to declare thresholds per column (if they so desire).

## Clarifying Questions
- What is the ideal output for this function?
    - Are we wanting to return a boolean dataframe?
    - Are we wanting to return a *filtered* dataframe based on a condition?
- I'm trying to understand how this would be used:

    ```python
    In [1]: df = pd.DataFrame(
        ...:     {'a': [0.75, 2.25, 2.5], 'b': [2, 5, 8], 'c': [300, 303, 306]}
        ...: )

    In [2]: df
    Out[3]:
          a  b    c
    0  0.75  2  300
    1  2.25  5  303
    2  2.50  8  306

    In [3]: df.diff()
    Out[3]:
          a    b    c
    0   NaN  NaN  NaN
    1  1.50  3.0  3.0
    2  0.25  3.0  3.0

    In [4]: flags = df.diff().gt(2)

    In [5]: flags
    Out[5]:
           a      b      c
    0  False  False  False
    1  False   True   True
    2  False   True   True
   ```

    - Is the intended use here to show the entire dataframe with the flags filter?
    
    ```python
    In [6]: df[flags]
    Out[6]:
        a    b      c
    0 NaN  NaN    NaN
    1 NaN  5.0  303.0
    2 NaN  8.0  306.0
    ```

    - Or, to use a specific column within flags to filter the original dataframe?

    ```python
    In [7]: df[flags['b']]
    Out[7]:
          a  b    c
    1  2.25  5  303
    2  2.50  8  306
   ```

    - I guess my question here is what "cleaning" process will this do? If we return the entire boolean **dataframe** the user can manipulate it at will and can do the filtering based on the column within `flags` that they choose.
    - If this is really to be applied for a single column, we could handle that as a columnar function. This would filter the dataframe based on a *single* column condition provided by the user.


Sorry for the long comment 😊 , but any input you have would be really helpful!

Thanks!

**Comment by ericmjl** [comment]
Hey @loganthomas! Thanks for all the thought you've put in to thinking about this issue. Having read through it, I find it very well-considered. 

Let me first summarize what I think the main issues are:

1. What categories of criteria should there be in the function? 
2. Is this a columnar or dataframe-wide operation?
3. What's the output for this function?

And then from that, the API design comes through as well, which I'll address along the way.

## What categories of criteria?

By listing out clearly the "categories" of criteria, we can also shape the API more clearly:

- `direction`: Probably one of `increasing`, `decreasing`, None (or `any`)
- `scale`: `absolute`, `percentage`
- `threshold`: some numeric value

## Is this columnar or dataframe-wide?

I have a strong hunch that given the most use cases we'll see, it'll be columnar.

## What is the output for this function?

I think the output for this function should be appended columns. That's what `flag_nulls` does, so I think the `flag_X` functions should be having as a boolean transformation on a column, based on some criteria, followed by an appending to the original dataframe. Returning a boolean dataframe will cause the program to lose information on the original dataframe. 

## Possible API design

Having let the idea bounce through my head, I am seeing the following API design:

```python
df.flag_jumps(scale="absolute", direction="increasing", threshold=2)
# This satisfies the use case where the criteria has to be applied across _all_ columns uniformly.
# This appends `k` columns to the dataframe, each named `f"{column_name}_jump_flag".

df.flag_jumps(
    scale=dict(col1="absolute", col2="percentage"),
    direction=dict(col1="increasing, col2="any"), 
    threshold=dict(col1=1, col2=2),
)
# This is the more general case, and satisfies the use case where different criteria are applied across different columns.
# This adds two columns, one called `col1_jump_flag`, and the other called `col2_jump_flag`.
```

Underneath the hood, I'm pretty sure the order of operations is quite sane. For example, it seems to me that choice of scale comes first (i.e. percentage change or diff will come first), then direction, then threshold.

What do you think, @loganthomas? Does this help clarify/organize, or have I just muddled the water more 😹?

**Comment by loganthomas** [comment]
@ericmjl 
Awesome! Makes sense... I'll start coding this up as my time allows. Appreciate the guidance!
