### ISSUE TITLE
new function proposal: find and replace

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#93]
Colleague proposed this function: within a column that houses strings, within each cell, provide a `find_replace()` function that finds a substring in the cell, and replaces it with another substring.

Note to self:

- Figure out if this is already possible with pandas.
- Decide if implementing this provides a more fluent function API.

**Comment by zbarry** [comment]
Should it support regular expressions? 
🤔

**Comment by szuckerman** [comment]
Regex is ok.... but globbing is nicer:

https://docs.python.org/3.6/library/fnmatch.html

**Comment by szuckerman** [comment]
The above looks good, except “exact” is unnecessary.  Regex or glob without wildcards will be equivalent.

**Comment by szuckerman** [comment]
So they’re kind-of different things. I think this answer can give a better description of the differences than I could write here: 

https://askubuntu.com/questions/714503/regular-expressions-vs-filename-globbing

In general, when searching for things I find globbing more useful (cause you just need an asterisk) but for validation regex is better because one can be more precise with what is expected.

**Comment by zbarry** [comment]
Yeah 90% of the time I just use globbing. I only use regex when I absolutely have to. No idea how often you would need them in pandas-style applications.

**Comment by ericmjl** [comment]
Ok! Synthesizing the discussion thus far:

```python
def find_replace(df, find, replace, kind='glob'):
    """
    # docstring opener above
    Whether or not you use kind="glob" or "regex", if you do not use any wildcards,
    it will default to an exact match. We expect an 80/20 split between exact/wildcard
    usage, and with globbing being more easily understood than regexes, it is hence
    the default choice.
    # continue docstring below
    """
    kinds=['regex', 'glob']
    if kind not in kinds:
        raise ValueError(f'kind kwarg has to be one of {kinds}')
    if kind == 'regex':
        # implementation goes here
    else:
        # implementation goes here
    return df
```

Comments?

**Comment by zbarry** [comment]
Needs a `column_name` / `col_name` (?), right?

**Comment by ericmjl** [comment]
> Needs a column_name / col_name (?), right?

Thank you. Updating...

**Comment by zbarry** [comment]
Also think that maybe `col_name` should come before `find` and `replace` in the args list... From the at-a-glance understanding perspective, maybe `df.do_this(to_this, with_this_particularly)` is more in line with what we have done with other functions.
